### ISSUE TITLE
Achtergrondkaart in tiling service in grijstinten

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#10]
Een en ander heeft betrekking op de webkaart in ontwikkeling. Naast de bestaande luchtfoto-tiling (al dan niet met overlay), de Google wegenkaart-tiling en de uiterst fijne OSM-tiling mis ik een achtergrondkaart in grijstinten. Met name voor de kleurenblinde medemens is een (groene) luchtfoto alsook de fullcolor tiling service van Google en OSM soms erg hinderlijk in combinatie met het kleurenpalet dat de netkaart zelf ook gebruikt. Een achtergrond van bijvoorbeeld OSM in grijstinten zou dit probleem bijna volledig oplossen en zou een handige toevoeging zijn.

**Comment by BaDu-HSN** [comment]
Fixed
