### ISSUE TITLE
Bijzondere karakters in sidebar ballons worden niet corrrect weergegeven

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#106]
![afbeelding](https://cloud.githubusercontent.com/assets/21307438/23452630/4937e746-fe65-11e6-80da-0ebfa5fff3f8.png)
Het betreft vertaalde kreten

**Comment by BaDu-HSN** [comment]
CLOSED

**Comment by HansNien** [comment]
Helaas toch te heropenen. Hoewel de ruit met het vraagteken is verdwenen, is er nu een ander soort fout voor teruggekomen. 

![bijzondere tekens nog steeds niet je van het](https://cloud.githubusercontent.com/assets/23345566/23991259/f0ceeeb2-0a38-11e7-8c5a-85399d28f8b0.JPG)

**Comment by BaDu-HSN** [comment]
Issue moved to https://github.com/Hoogspanningsnet/Webkaart-scripts/issues/120
CLOSED here
