### ISSUE TITLE
Attribution mist soms link naar de mainsite

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#109]
Bij de meeste ondergronden (zoals de luchtfoto) is er via het attribution-icoon geen link aanwezig naar de mainsite. Zonder het openklikken van het instellingenmenu is er dan geen enkele directe link richting de mainsite aanwezig. Vraag/verzoek is of het attribution-icoon bij aanklikken onafhankelijk van welke achtergrond er gebruikt wordt altijd een aanklikbare link naar de mainsite kan dragen.

**Comment by BaDu-HSN** [comment]
Vermoedlijk is dit alleen op kleine schermen het geval, op mijn laptop heb ik altijd een link naar de mainsite in beeld.

**Comment by HansNien** [comment]
Dat is dan heel apart, het viel me op op een computerscherm van rond de 1200 pixels breed. 

![attribution](https://cloud.githubusercontent.com/assets/23345566/23580279/6ade5826-00fe-11e7-8e34-a83b9a81e0d2.jpg)

**Comment by BaDu-HSN** [comment]
Sorry ik zat op de verkeerde URL te kijken, comment in nu aangepast.
CONFIRMED

**Comment by BaDu-HSN** [comment]
CLOSED
