### ISSUE TITLE
Webkaart toont jaar van ingebruikname stations niet

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#11]
Bij aanklikken van een stationslabel verschijnt de tekstballon zoals bedoeld, maar het veld In bedrijf en het veld Uit bedrijf lijken niet te worden ingelezen. Ingevulde en dus aanwezige informatie (voorbeeld: Klazienaveen Zwet, in gebruik sinds 2012 tot op heden) heeft in de interface van GE deze waarden netjes in de ballon staan terwijl deze in de interface van de webkaart niet wordt getoond.

**Comment by BaDu-HSN** [comment]
Oops, niet netjes.
Ik wacht even op het gereedkomen van de nieuwe balloons (Mark werkt aan de CSS)

**Comment by BaDu-HSN** [comment]
FIXED
