### ISSUE TITLE
Feedbackformulier via link in instellingenmenu geeft javascriptfout

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#111]
Bij aanklikken van de link in het instellingenmenu (het niet-speciefieke feedbackformulier) verschijnt er niets, behalve onderin beeld deze melding:

![feedbackformulierfout](https://cloud.githubusercontent.com/assets/23345566/23591708/14fbe926-01f5-11e7-9e5a-143eae273533.JPG)

Browser: FF in Windows 7, op de classic windows look gezet vanwege grafische performance.

**Comment by BaDu-HSN** [comment]
Dubbel met https://github.com/Hoogspanningsnet/Webkaart-scripts/issues/108
CLOSED
