### ISSUE TITLE
Transportcapaciteit (veld) niet tonen of 'onbekend' weergeven bij niet ingevuld

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#112]
Bij verbindingen is de transportcapaciteit wel eens onbekend, met name in het buitenland. Bij het veld in kwestie staat nu gewoon MVA zonder voorvoegsel. Oogt wat gek. Verzoek is of er een defaultwaarde kan worden ingesteld die (onbekend) luidt, of dat we gewoon het hele veld verbergen indien er niets is ingevuld.

**Comment by BaDu-HSN** [comment]
Done, meteen aangepast voor stroom van railsysteem bij stationsterreinen.
