### ISSUE TITLE
Updaten veld Opmerkingen toont een reeds bestaande opmerking niet

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#113]
Bij het aanpassen of updaten van een station (label met pictogrammen) wordt het veld Opmerkingen leeg weergegeven, ongeacht of er voorafgaand aan de invoervelden-update van 10-03 al iets stond ingevuld of dat het veld nog leeg was. Het lijkt erop dat bestaande invoer niet wordt weergegeven.

**Comment by BaDu-HSN** [comment]
CONFIRMED in de Stationsiconen edit.

**Comment by BaDu-HSN** [comment]
Veldnaam in de database-tabel is Opmerking ipv Opmerkingen
CLOSED
