### ISSUE TITLE
Toevoegen van link met 'credits'

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#114]
In het menu Instellingen kan onderdaan een een nieuwe link worden opgenomen met naam 'credits' of mogelijk gewoon 'colofon'. Dit hing al eerder in de wacht, maar sinds het colofon op de mainsite klaar is en live staat kan het nu doorgevoerd worden. 

De correcte link: http://www.hoogspanningsnet.com/about/colofon/

**Comment by BaDu-HSN** [comment]
CLOSED
