### ISSUE TITLE
Soms komt er een max_user_connections exceeded melding vanuit MySQL

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#116]
Lijkt er op dat de verbindingen niet correct worden afgesloten.
Checken wat maximum is.

**Comment by BaDu-HSN** [comment]
Lijkt niet echt veroorzaakt te worden door onze scripts. 
Wel nogmaals checken of connecties steeds netjes worden afgesloten in de scripts.
Gracefull exit (nette foutmelding) bij fout implementeren.

**Comment by HansNien** [comment]
Vanmiddag had ik er weer eentje. Eerst verscheen in de ballon (bij poging tot editen) 'geen connectie met MySQL'. Een nieuwe ballon opvragen later verscheen de onvolprezen, ongrijpbare maar nu toch een keer betrapte max_user_connections. Zoals gewoonlijk herstelde de situatie zichzelf weer.

![max_user_connections error](https://cloud.githubusercontent.com/assets/23345566/24915441/69b02fdc-1ed7-11e7-90d6-41339025ca0d.JPG)

**Comment by HansNien** [comment]
Heeft deze hickup zich nog een keer laten zien of is het probleem vooralsnog als beheersbaar aan te merken? Ik heb 'm zelf sindsdien niet meer gezien.

**Comment by BaDu-HSN** [comment]
Geen meldingen meer van gezien.
Ik zal nog wel een meer gracefull exit proggen in de balloon.

Bij de netkaart items doe ik verder niets, de kaart laadt dan gewoon niet, een refresh door de gebruiker levert weer een werkende kaart op.

**Comment by BaDu-HSN** [comment]
Fixed, CLOSED
