### ISSUE TITLE
Verwijzingen release-notes naar shortlist

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#119]
Op dit moment verwijst de link in de webkaart naar de longlist. Misschien is dat wat overkill omdat de longlist eigenlijk alleen voor de zware power techies bedoeld is. De shortlist (de tabel) is meer gericht op de normale gebruikers. Verzoek is dan ook om in eerste instantie daarheen te verwijzen.

http://www.hoogspanningsnet.com/netkaart/releasenotes-shortlist/

**Comment by BaDu-HSN** [comment]
CLOSED
