### ISSUE TITLE
Default verbergen veld Land in de tekstkolom

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#121]
Het veld Land heeft weinig meerwaarde in de tekstkolom omdat het meestal een open deur is. Slechts offshore zonder zicht op aansluitkabels is het van een kleine meerwaarde. Verzoek is of dit veld verborgen kan worden in de kolommen.

**Comment by BaDu-HSN** [comment]
Voor ons wellicht een open deur, maar dat geldt niet voor onze gebruikers van buiten west europa (en die zijn er)
