### ISSUE TITLE
Defaultwaarde in pulldownmenu Stationstype op Trafostation zetten

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#122]
In de Excelsheet was de suggestie gedaan voor een _(maak een keuze)_ als defautwaarde, waarna het veld nog leeg zou blijven. Hier heb ik me verkeken op de schaal van het geheel: we hebben duizenden stations in de kaart staan waar nu allemaal niets staat ingevuld bij het stationstype. Bij 95% van de stations is er sprake van een trafostation (met transformators en twee of meer spanningen) zodat het veel werk zou schelen als de defaultwaarde voor dit veld op _trafostation_ kan worden ingevuld.

**Comment by BaDu-HSN** [comment]
Ik kan natuurlijk ook de waarde trafo station invullen wanneer de spanningen van het icoon er meer dan 2 zijn en wanneer de spanningen niet 380-220 of 150 zijn (want dan is het een koppelstation).
Wellicht zijn er meer voorwaarden?

**Comment by HansNien** [comment]
Ah, dat zou nog beter zijn. :-) 
Enige vraag die dan nog open blijft en waarop jij het antwoord vast beter weet dan ik: noemt men een station een koppelstation als er _uitsluitend_ koppelnetspanningen zijn, of als er op zijn minst één koppelnetspanning aanwezig is die contact maakt met een niet-koppelnetspanning? (Beide lijken voor een logische regel geschikt, maar we moeten wel de correcte hebben.)

**Comment by BaDu-HSN** [comment]
Tennet hanteerd (niet helemaal expliciet) de volgende definitie:
- Trafo die twee netspanningen van TenneT aan elkaar koppelt (een koppeltrafo)
- Trafo die een regionaal netbeheerder voedt (een trafo station)
De RNB's kennen volgens mij alleen trafostations.
Dus een koppelstation is een verbijzondering van een trafostation welke in NL alleen door TenneT gebruikt wordt voor 380/220 - 380/150 - 380/110 - 220/110 stations. Alle andere stations zijn trafostations.
Hoe dat in het buitenland (bijv DLD) wordt genoemd zou ik niet weten, maar we zouden de regel kunnen doorvoeren, het wordt dan ook onze definitie.

**Comment by HansNien** [comment]
Dank, duidelijk. Eigenlijk wel iets om in mee te gaan. Tenslotte ligt de basis van de netkaart in Nederland en België, dus de definitie die hier geldt mag tot op zekere hoogte worden meegenomen. Wat mij betreft mag deze definitie graag doorgevoerd worden. (Note to myself: in de netkaartbijbel stoppen.)

**Comment by BaDu-HSN** [comment]
Het is nu geworden:
Als er niets is ingevuld en er een 'anders/onbekend' mogelijk is in de dropdown wordt die geselecteerd.

Het is helaas erg lastig om andere voorwaarden te programmeren.

**Comment by BaDu-HSN** [comment]
CLOSED
