### ISSUE TITLE
Mastpositie geforceerd van alle circuits ontdoen?

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#123]
Bij onttakelde masten waar een GSM-mast van is gemaakt, of die als relict ergens zijn blijven staan, worden soms nog de circuits weergegeven die bij de mastpositie hoorden in de laatst bekende situatie toen de mast nog in dienst was. Het betreft enkele tientallen exemplaren in Nederland. Je kan een mast waaraan eenmaal circuits zijn toegekend niet meer 'leeg' krijgen.  Is er iets te bouwen waardoor een mast geforceerd kan worden leeggehaald? (Bijvoorbeeld door, zeg eens wat, het circuitveld te overschrijven met een circuit met code v0000, waarna het script begrijpt dat de mast dan leeg is?)

**Comment by BaDu-HSN** [comment]
Hmmmm, dat is echt een BUG. Kennelijk worden ook de circuits geselecteerd die al uit bedrijf zijn.
Kwestie van de query aan passen met een extra voorwaarde in de where:
AND Year(now))<=JaarUitbedrijf

**Comment by BaDu-HSN** [comment]
CLOSED
