### ISSUE TITLE
Ongewenste selectie van informatiekolom bij muisgebruik/klik

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#124]
Klein euveltje waarvan ik niet goed weet of het als bug gezien moet worden of hooguit als enhancement. 
Bij het aanklikken van een object verschijnt de informatiekolom. Klik je daarna ergens willekeurig in de kaart maar wel buiten een ander object (gewoon ergens in een weiland) om te slepen of te verplaatsen, dan wordt automatisch de tekst en invoer in de getoonde kolom geselecteerd zodat deze blauw wordt. Dat verdwijnt pas weer na in de kolom zelf te hebben geklikt. Dit is enigzins irritant.

**Comment by BaDu-HSN** [comment]
Hoe het ook zij, het is een beetje irritant. 
Welk gedrag zou je willen zien (zonder garanties dat het kan) Verdwijnen van de sidebar? (je klikt immers op een plek zonder object)

**Comment by HansNien** [comment]
Verondersteld dat het kan, dan zou inderdaad het weer verdwijnen van de kolom ideaal zijn. Als dat niet kan, dan is het simpelweg 'niet' selecteren van de tekst ook al een verbetering.

**Comment by BaDu-HSN** [comment]
CLOSED

**Comment by HansNien** [comment]
Heropend (zie de app). Aan de beschrijving bij de opening is niets veranderd qua gedrag of optreden, het probleem/euvel is identiek.

**Comment by BaDu-HSN** [comment]
De selectie in de balloon was gedekt maar de selectie treed ook op op andxere plekken in de webkaart.
De unselect van tekksten op een andere plek onderbrengen dus (event afterMove oid?)

**Comment by HansNien** [comment]
Het selectiegedrag lijkt overigens iets(je) te verschillen. Firefox is het extreemst, daarin wil het wel eens gebeuren dat zelfs de stationsnamen zelf geselecteerd worden. Bij Chrome moet je meer je best doen en dingen forceren door opzettelijk de muis als een rodeostier over de muismat te bewegen voordat het probleem optreden wil. Probleem is dus hoofdzakelijk FF.

![selectie-error in ff](https://cloud.githubusercontent.com/assets/23345566/25133215/514dc54c-244c-11e7-839f-951d6fff867a.JPG)

**Comment by BaDu-HSN** [comment]
Dit treed voopr zover ik kan zien alleen op bij firefox.
Een workaround is even een rechtsklik met de muis te doen, dit deselecteert de ellende

**Comment by BaDu-HSN** [comment]
Een eventuele selectie na een move/drag zou nu heel even zichtbaar moeten zijn en meteen weer verdwijnen.

**Comment by BaDu-HSN** [comment]
CLOSED (Again)
