### ISSUE TITLE
Onderscheid AC en DC bij gelijke spanning komt soms niet goed door in de mappenboom

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#126]
In Denemarken treffen we 400 kV zowel in AC als in DC aan, beide behorend tot het koppelnet. In de mappenboom zichtbaar in GE blijkt dat alle 400 kV is samengenomen in één groep die onder DC terecht is gekomen. Voor de weergave maakt dit niet uit, maar in de mappenboom en mogelijk ook in de database is dit niet correct.

![deelnet soms niet correct in de mappenboom](https://cloud.githubusercontent.com/assets/23345566/24457914/cfd278a0-1497-11e7-8b8b-7d97282d3f61.JPG)

**Comment by BaDu-HSN** [comment]
Ik kijk er naar, met de gewijzigde subtype definitie is hier een ongewenst neveneffect opgetreden.

**Comment by BaDu-HSN** [comment]
CLOSED
