### ISSUE TITLE
Vertalen termenlijst de.txt naar en.txt

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#130]

**Comment by HansNien** [comment]
Vertaling termenlijst de.txt naar en.txt is gereed. Tevens is er een nds.txt (Niedersaksisch) gemaakt. _Waorum? De taol waormet da'j opgreuid bunt giet je merakels an 't hart en 't muuk me gramieterig dat we slim veul meuite döt veur 't opduukeln van Duuts en Fraans, maor indewiel oes dialect schier vrömd blef. Kiek maor wa'j d'r met anvangt._  ;-)

**Comment by HansNien** [comment]
[en.txt](https://github.com/Hoogspanningsnet/Webkaart-scripts/files/892285/en.txt) (Engels)

[nds.txt](https://github.com/Hoogspanningsnet/Webkaart-scripts/files/892287/nds.txt) (Niedersaksisch volgens de SONT-spellingswijze)

**Comment by BaDu-HSN** [comment]
Hahaha geweldig die nds.txt, prachtig!!
Wat mij betreft kan ie zo de webkaart in 😄

**Comment by BaDu-HSN** [comment]
Ik zie in de en.txt nog wel een paar dingen die iets minder netjes vertaald zijn of anders wellicht beter zijn:
- de ene keer is een mast een pole de andere een tower, een term kiezen zou beter zijn
- aantal velden=Number of bays
- afspanmast is wellicht beter om Anchor tower te gebruiken
- operation voltage  is operating voltage
- Bipool=Bipole (geen bipolar)
- Frequency changer=Frequency converter
- Koppelveld=Bus coupler (of Coupler bay)
- Ongeldige landcode=Invalid country code
- Opstijgpunt=Line-to-cable transfer (of Cable riser)
- Pas uw criteria aan=Please change your query
- Spoelveld=Reactor bay
- Subtype=Subtype
- Trafostation=Transformer substation
- Tweevlaksmast=Double horizontally configured pylon
- U kunt de voortgang=You can track the progress of your ticket
- Viervlaksmast=Four-levelled horizontal configured tower (ik mis bij drievlaks en twee vlak het deel three-levelled etc)
- Search the Gridmap
- Italië=Italy

**Comment by BaDu-HSN** [comment]
CLOSED
