### ISSUE TITLE
Vertalen termenlijst de.txt naar fr.txt

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#131]

**Comment by BaDu-HSN** [comment]
Ik heb de lijst inmiddels via het forum verstuurd naar Bavo met de vraag of hij er eens naar kon kijken.
De bestanden de.txt en en.txt heb ik daarbij ter inspiratie meegestuurd.

Ook even de vraag gesteld of er een vlaamse vertaling nodig is.

**Comment by HansNien** [comment]
Dank voor het initiatief. Ik ben benieuwd, vooral m.b.t. Vlaams.
Dan laat ik 'm verder even met rust.

**Comment by BaDu-HSN** [comment]
Voorlopig frans even uitgezet als vertaling. shrek heeft het erg druk.
