### ISSUE TITLE
Feedback issue in github voorzien van meer data

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#136]
Nu wordt in het feedbackbericht (issue) op Github alleen het ID weergegeven.
Het zou beter zijn als we minimaal het type en de naam van de ID weergeven.
Dus in onderstaand voorbeeld ook Stationsicoon en bijv.  Botlek weer te geven.

![image](https://cloud.githubusercontent.com/assets/21307438/24577016/51b65aaa-16c6-11e7-9e11-a86eb8260866.png)

**Comment by BaDu-HSN** [comment]
Als je het helemaal mooi wilt maken voeg je een link in het bericht toe waarmee je de webkaart opend op de juiste plek.
*speelt toekomstmuziek

**Comment by HansNien** [comment]
Wanneer een objectnummer wordt ingegeven is aan de beginletter te zien welk soort object het betreft, maar als het bijvoorbeeld om een 110 kV-circuit gaat kunnen dat er duizenden zijn. Als degene die commentaar aanleverde alleen zegt 'wordt bedreven op 60 kV', dan weten we nog niks, en is het juiste object pas te traceren via een sluipweg, namelijk door in de beheerdersomgeving via de wis-mogelijkheid in het laatste-waarschuwing-venster de roepnaam af te lezen van het object, en daarna No I have doubts in te drukken om veilig weg te komen... Een oplossing is mogelijk het zoekveld objectnummergevoelig maken.

**Comment by BaDu-HSN** [comment]
Hmmm goeie suggestie en eenvoudige te implementeren in de webkaart.
Verder wil ik eigenlijk de ID in het issue een link laten zijn naar de balloon van dat betreffende item, dus bijvoorbeeld:
ID: [m8143](url=http://netkaart.hoogspanningsnet.com/balloon3.php?ID=m8143)

**Comment by BaDu-HSN** [comment]
CLOSED
