### ISSUE TITLE
Import naar lux netkaart

### ISSUE THREAD

**Issue by Knarvel** [Hoogspanningsnet/Webkaart-scripts#137]
Import naar lux netkaart vereist de landnaam LUX, en dit komt zonder probleem in de db.
Als je nu een willekeurig objekt ge-editeerd wordt deze 3-letterig afkorting niet meer geaccepteerd en moet ik de x wissen om andere modificaties ge-enterd te krijgen. Als het ff kan graag alles 2-letterig maken aub

**Comment by BaDu-HSN** [comment]
Alle tabellen in de database aangepast naar LU 
(2-lettercode zijn conform de netkaartbijbel)
Fixed & CLOSED
