### ISSUE TITLE
Vertalen termenlijst en.txt naar dk.txt

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#140]
Aangezien we die concessie ook willen dekken. Dréens lijkt wel wat op Deens, _maor da'j met mekaor 'n schier zeggien doon kunt_ of dat je het lezen kan wil nog niet zeggen dat je het kan schrijven. Ik ga daarom proberen om Ole Nielsen (forumnaam Elo) er eens naar te vragen, hij is tenslotte Deens. Als status lijkt me dit een could-have die allicht niet voor V6.0 gerealiseerd zal zijn.

**Comment by BaDu-HSN** [comment]
Go your gang zeggen ze in het steenkolen land.
Iig een nuttige aanvulling.
Zoals eerder gezegd is het toevoegen van een vertaling een fluitje van een cent:
- Taalbestand vertalen (het meeste werk)
- Nieuw taalbestand uploaden naar de webkaart (3 seconden werk)
- Een regel code toevoegen aan de taalkeuze in het instellingen menu van de webkaart (30 seconden werk)

**Comment by BaDu-HSN** [comment]
Nog iets gehoord van Elo? Of ga je toch je telefoon inschakelen?

**Comment by HansNien** [comment]
Geen reactie op de PM gehad. Plan B is een email sturen, maar dat gebeurt wel als de drukte rond de lancering an sich over is. Deze wordt 'm niet voor V6.0.

**Comment by BaDu-HSN** [comment]
Ik zou ook even mn vader kunnen vragen indien we van Elo geen reactie krijgen

**Comment by HansNien** [comment]
Hmm, da's waar ook. In het fraaie Randers, als ik het me goed herinner. Maar dat is wel een erg rare vraag om te stellen die ook nog eens tijd kost en wat kennis van het jargon vereist. Eerst maar eens zien of Ole op een mailtje reageert. Scheelt dat e.e.a. niet direct haast heeft.

**Comment by BaDu-HSN** [comment]
DONE and CLOSED
Vertaling gedaan door forum gebruiker HaDu
