### ISSUE TITLE
Invoeren van sommige ontbrekende vertaalde termen in de taalbestanden

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#141]
In de taalbestanden ontbreken her en der termen die wel een vertaling behoeven, zoals (ter voorbeeld) het reeds in de app genoemde tonmast. Die is in iedere taal weer anders (barrel pylon, tonnenmast, tønde, tun, ...) en kan daardoor probleemloos in de taalbestanden van iedere taal die we aanbieden op dit moment. Via het beschreven pad en de juiste branch kunnen Mark en ik dat eventueel zelf doen (consequent wezen en ieder taalbestand meenemen bij toevoeging van een term), maar de vraag is of dat zomaar kan omdat het op een extra regel uitdraait waarna alle onderstaande regels een getal zakken. Is dat een probleem?

**Comment by BaDu-HSN** [comment]
Het toevoegen van een term is geen enkel probleem, voeg hem gewoon op alfabet toe.

Wel speelt er een ander iets:
De Tonmast staat in in de dropdown van mastmodellen en die kan je dus ook niet invoeren.
Dat komt omdat ie ook niet in de excelsheet die voor de balonnen is gemaakt voorkomt.
Moet ie daar worden toegevoegd?

**Comment by BaDu-HSN** [comment]
Even kleine toelichting over hoe het taalbestand werkt:
Het taal bestandis een willekeurige verzameling van strings bestaande uit
<NL begrip>=<vertaald begrip>
Wanneer een vertaling nodig is wordt gezocht door de NL begrippen en indien deze is gevonden wordt het vertaalde begrip geretourneerd.
Het zoeken is letterlijk, dus met hoofd en kleine letters spaties etc.
Wanneer een NL begrip niet wordt gevonden in de lijst wordt het originele begrip geretourneerd en wordt er dus niet vertaald.
Doordat er steeds door de hele lijst wordt gezocht is er geen index oid aanwezig en kunnen de begrippen in volledig door elkaar staan.

Het taalbestand wordt eenmalig ingelezen tijdens het starten van de webkaart (en na wijzigen van de taalinstelling). Een wijziging/tovoeging aan het taalbestandd komt dus op de webkaart niet meteen door. Even refreshen helpt dan wel.

Het taalbestand wordt iedere keer uitgelezen bij opvragen van een balloon of editscherm, daar komen wijzigingen dus wel meteen door.

**Comment by HansNien** [comment]
![tonmast vergeten](https://cloud.githubusercontent.com/assets/23345566/24743603/2b6c77a2-1aaf-11e7-9394-24025b6ff2d9.JPG)

_...damn!_ :-D
Okee, mijn schuld, die is dus inderdaad gewoonweg oldskool over het hoofd gezien. Ale je hem wil toevoegen in het pulldownmenu zorg ik er wel voor dat de reeds aanwezige taalbestanden de term erbij krijgen op alfabetisch de juiste plek. Dank voor de omschrijving van de functionaliteit van de taalbestanden, dat maakt de zaak een stuk duidelijker.

**Comment by BaDu-HSN** [comment]
Tonmast toegevoegd, nog andere termen die via een vertaling moeten lopen?
(het zou kunnen dat ik af en toe een tekst per ongeluk niet via de vertaal functie heb laten lopen)

**Comment by BaDu-HSN** [comment]
Geen nieuwe suggesties hier gezien, ze kunnen gewoon in het taalbestand worden ingevoegd.
Deze gaat dicht
CLOSED
