### ISSUE TITLE
Leesbaarheid mastnummers en stationsnamen

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#146]
Van een zeker persoon uit de regio Zwolle die bij een bepaald pretpark werkt (daar zijn er twee van, in dit geval vriend B van de 3D) en die de betaversie van de webkaart kent, kreeg ik deze binnen: 

![leesbaarheid_mastnummers](https://cloud.githubusercontent.com/assets/23345566/25045670/aed464fe-212d-11e7-8bde-46c0efd70c7c.JPG)

Heeft uiteraard betrekking op de web-interface. Voor V6.0 lijkt dat te laat (het is immers T-17), maar voor versie 6.1 kan het iets zijn om eens over na te denken of en hoe we dit kunnen oplossen. Net als met de namen van stations, misschien wat gloei of wat schaduw erachter zoals Google Earth dat ook doet.

**Comment by BaDu-HSN** [comment]
Ik heb wat geexpirimenteerd maar dit oplossen is niet makkelijk zonder andere kleuren weer minder zichtbaar te maken. Is deze aanpassing nog nodig??

**Comment by HansNien** [comment]
Hel treedt vooral op als de verbinding zelf oost-west loopt en precies onder de nummers terechtkomt. Daar lijkt vooralsnog geen elegante oplossing voor zonder een ruintelijk rommeltje te creëeren: bij twee parallel lopende verbindingen moet je wel kunnen herleiden welk nummer bij welke lijn hoort. Sluit deze maar tot nader order: een mastpositienummer is minder belangrijk dan stations- of knooppuntnamen en wie het mastnummer toch nodig heeft moet dan maar even iets beter kijken.

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#40
