### ISSUE TITLE
Veranderen woord 'Hanstaal' naar 'Nedersaksisch'

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#147]
In ieder geval voordat V6.0 online gaat. Hoewel Niedersaksisch (correcte spellingswijze in het Nederlands is _Nedersaksisch_) voor mensen ten zuiden en westen van de IJssel vaak op de lachspieren werkt, is het wel zo netjes het beestje bij de correcte naam te noemen.

**Comment by BaDu-HSN** [comment]
CLOSED
