### ISSUE TITLE
Onderzoeken of het mogelijk is in GPS-tracking mode dhet scherm niet uit te schakelen

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#148]
Zodat we de kaart een beeld blijven houden

**Comment by coreice** [comment]
Onder iOS lijkt dit momenteel een lastig verhaal (i.e. niet mogelijk): http://stackoverflow.com/a/41134821

**Comment by BaDu-HSN** [comment]
Vanuit javascript is het aanspreken van het OS niet mogelijk, je kan alleen de browser aanspreken, hierin kan je weer geen screensaver settings aanspreken.
Dit is onafhakelijk van platform of browser.

Kortom helaas niet mogelijk.

ps:
Wel als we ooit een app ontwikkelen voor de netkaart :)
