### ISSUE TITLE
Aanpassen van de tekst 'Oetvoering' (Nedersaksisch) in de headerbalk naar 'Uutvoering'

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#149]
Wegens incorrect, dit kan echt niet. Zo heb ik die niet aangeleverd. ;-)

Aangezien ook de tekst (v5.1b) er nog af moet en naar 6.0 moet, meen ik dat dit er nog wel bij kan.

**Comment by BaDu-HSN** [comment]
Het is een kwestie van het taalbestand aanpassen, daar staat de term al in.
De versie naar 6.0 tillen is een kwestie van het configuratie bestand aanpassen.

**Comment by BaDu-HSN** [comment]
Fixed, CLOSED

**Comment by BaDu-HSN** [comment]
Fixed, CLOSED
