### ISSUE TITLE
Open tekstveld in object knooppunt werkt niet goed

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#152]
Bij het invoeren van tekst in het opmerkingenveld van de objectgroep Knooppunten krijg je na het doorvoeren de tekst terug 'Invalid query', waarna de aanpassing aan het open veld niet wordt meegenomen. De andere velden zoals jaartal blijken wel aanpasbaar te zijn.

**Comment by BaDu-HSN** [comment]
Fixed: Was een verkeerde veldnaam in de edit (Opmerkingen ipv Opmerking).
CLOSED
