### ISSUE TITLE
Bij invullen van informatie wordt een leeg/default doorgevoerd

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#155]
Zojuist bij het invoeren van wat nieuwe informatie bij een stationsterrein (hoogste spanning op ENCI) werd de parameter _Constructiewijze_ en de parameter _Railconfiguratie_ niet aangeraakt. Die waren ook nog door niemand anders ingevuld. Echter, na het doorvoeren van de hoogste spanning werd de defaultwaarde in het pulldownvenster opeens veranderd van 'station' naar 'Hangende rails'. Dat is niet correct en bij onbekende stationstypes kan niet meer terug voor _onbekend_ gekozen worden.

Kunnen we in deze velden ofwel een blanke invoer als default instellen, of in de beide velden als bovenste waarde (die default wordt geselecteerd als je het bewerkvenster opent) respectievelijk _station_ en _onbekend_ toevoegen, zodat die automatische keuze dan in elk geval geen onjuistheid bij onbekende situaties meer toont?

**Comment by BaDu-HSN** [comment]
Vereist wat odnerzoek, maar zou wel mogelijk moeten zijn. Maakt eea wel wat ingewikkelder.
Nu was de gedachte : als het veld een waarde beveat die niet in het keuze menu staat wordt een default waarde gebruikt om toch een waarde af te dwingen.
Eigenlijk wordt dat nu waarde niet wijzigen en gewoon handhaven.

**Comment by BaDu-HSN** [comment]
De huidige werking is gebaseerd op de velddefinties excel zoals in het verleden opgesteld. Als er een waarde in het veld staat die niet voorkomt in de dropdown wordt de default waarde gekozen en de oude waarde dus overschreven.

**Comment by HansNien** [comment]
Dus als ik het goed begrijp zijn er velden in de Excelsheet waarin wel een default leeg of blanco is opgenomen, maar er zijn ook velden waarbij dat niet is gedaan? Of nauwkeuriger: waarbij ik dat niet heb gedaan? (Nu de netkaartbijbel een opfrisser krijgt in aanloop naar cycle 7 moet ik de Excelsheet toch eens nalopen, maar de bestaande structuur moet wel zo veel als mogelijk is zo blijven.) Hou deze nog maar even open, ik moet eerst zelf de stap zetten om de excelsheet aan te passen aan Stations - Verbindingen - Productie. Dan kan hier meteen op gelet worden. Je hoort ervan.

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#39
