### ISSUE TITLE
ID-links bij ingeschoten tickets vanuit de netkaart openen niet in nieuw venster

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#157]
Bij het bekijken van ingeschoten tickets door gebruikers van de webkaart wordt netjes het ID-nummer meegestuurd, aanklikbaar en wel, zodat voor ons te zien is welk object het betreft. Helaas opent de ballonweergave inline niet in een nieuw venster, zodat je dan meteen Github kwijt bent. Is oplosbaar met rechtermuisknop, maar kan er ook iets veranderd worden op Github zelf zodat de ID-link in een nieuw venster opent?

**Comment by BaDu-HSN** [comment]
Goed idee, ik zal het verwerken

**Comment by Knarvel** [comment]
ipv een nieuw venster zou ik hiervoor een nieuw tabblad handiger vinden.

**Comment by BaDu-HSN** [comment]
Dat is een instelling van je browser zelf, ik voeg target="_blank" toe.

_blank 	Opens the linked document in a new window or tab
