### ISSUE TITLE
Emailadressen en namen van gebruikers feedbackformulier niet meer openbaar zichtbaar maken

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#158]
Althans, in Github, waar de meldingen terecht komen. Zie de reeds ingeklopte meldingen. Ik kan me voorstellen dat mensen daar in sommige situaties niet content mee zijn. Verder is er het argument van Frank, dat webcrawlers ook smullen van emailadressen. Is er een manier of mogelijkheid om de verzendergegevens niet openbaar te tonen?

Ik denk/weet dat dit erg ingewikkeld is, maar dat is geen reden om dit punt niet te willen maken of ter discussie te willen voorleggen.

**Comment by BaDu-HSN** [comment]
Goed punt, ik de volgende mogelijke oplossingen:
- We zouden gebruik kunnen maken van een Git die niet openbaar is maar wel gratis (gitlab ?)
- We zouden parallel aan Github ook een feedback database aan kunnen leggen waar deze gegevens wel in staan, alleen toegankelijk voor editors (het idee van Frank)

Andere suggesties zijn welkom

**Comment by Knarvel** [comment]
Maak een categorie op het forum aan in "eigen bedrijf" aan die alleen voor een groep editoren, beheerder, en moderators zichtbaar is. Ieder ticket creëert dan een nieuwe draad in deze categorie met het ticket als eerste bijdrage, waarna wij verder volledig vrij iedere nodige actie kunnen bespreken.

**Comment by BaDu-HSN** [comment]
Leuke suggestie, maar ik heb nog geen API kunnen vinden in onze forum software om dit vanuit de webkaart te kunnen doen.
We hebben destijds bewuest voor Github gekozen vanwege het gemak.

**Comment by Knarvel** [comment]
Helpt dit: https://www.phpbb.nl/forums/viewtopic.php?f=92&t=60782 ?

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#38
