### ISSUE TITLE
Webkaart invulvelden verliezen na aantikken voor invoer meteen focus

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#160]
Dit geschied iig op mijn mobiel.
Stappen:
- tik zoekicon aan
- selecteer invulveld
(toetsenbord verschijnt, maar verdwijnt ook meteen weer)

**Comment by BaDu-HSN** [comment]
Dit geschied niet alleen bij het zoekveld, maar ook de invulvelden van de sidebar, editten van object-info op mijn mobiel is dan ook niet mogelijk

**Comment by BaDu-HSN** [comment]
Oorzaak zit in demanier waarop firefox omgaat met het verschijnende toetsenbord, het wordt niet over de kaart getoond maar eronder, dit heeft als effect dat de kaart een andere extend krijgt en dus opnieuw getekend wordt.
Oplossing zou kunnen liggen in het terugzetten van de focus na een resize, of het blokeeren van de resize als er een invoerveld focus heeft.

**Comment by BaDu-HSN** [comment]
Dit lijkt meer voor te komen:
https://stackoverflow.com/questions/35769939/how-to-prevent-android-firefox-browser-to-resize-window-when-soft-keyboard-is-on

**Comment by HansNien** [comment]
Interessant, op mijn stokoude Sonim A9+ met Android 4.4.5 Kitkat doet alles het in Firefox gewoon naar wens. Intikken, toetsenbord, geen enkel probleem hier. Maar we houden het in de gaten.

**Comment by BaDu-HSN** [comment]
Is dit met de nieuwe versie van FF mobile nog actueel?

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#37
