### ISSUE TITLE
Foutmelding binnengekomen via de mailbox

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#163]
Zoals in de mail binnengelopen. Mail is vqn deze ochtend.

Emailadres	afz.hoogspanningsnet@visioen.nl
Onderwerp	Nieuwe netkaart
Bericht	Drie puntjes: - allereerst: grote complimenten!! - het feedbackformulier in de nieuwe netkaart geeft een foutmelding: "Notice: Undefined variable: itemgt in /home/deb99417/domains/hoogspanningsnet.com/public_html/webkaart/feedback.php on line 86 HACKING NOT ALLOWED!!!" - deze melding kreeg ik toen ik het volgende wilde melden: "Bij station Zevenbergschehoek (http://webkaart.hoogspanningsnet.com/#16/51.6835/4.6715) hebben jullie keurig ook de portaalmasten 39B en 39C vermeld. Op de 150 kV-lijn Breda - Roosendaal ontbreken de portalen van het netknooppunt Rioolseweg - tussen mast 74 en 75 (http://webkaart.hoogspanningsnet.com/#16/51.5978/4.6149)." Met vriendelijke groet, B

**Comment by BaDu-HSN** [comment]
hmmm ik zal eens kijken.

**Comment by BaDu-HSN** [comment]
De URL's naar de webkaart hadden tot gevolg dat de POST naar de server niet meer correct door kwam, dit is inmiddels gecorrigeerd.
