### ISSUE TITLE
Pictogrammen willen (wilden) niet goed laden

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#164]
Zomaar zonder enige aanleiding wilden willekeurige pictogrammen voor de mastbolletjes en de stationsiconen niet goed of niet volledig laden. Het betrof de webkaart. Het probleem duurde een halve minuut en zat rond 15.20 uur zojuist. Het uitzicht was als volgt:

![pictogrammen laden niet goed](https://cloud.githubusercontent.com/assets/23345566/25806316/0c0d7524-3403-11e7-8cc2-62140002570e.JPG)

Na mouseover verschenen ze dan alsnog stuk voor stuk. Na een stukje schuiven en daarmee refresh verschenen willekeurige andere exemplaren niet, ook van mastbolletjes die het een view eerder wel hadden gedaan. Na een halve minuut loste het hele probleem zichzelf zomaar op.
Het probleem is dus niet direct meer relevant, maar ik maak er wel even een melding van.

Het bug-label is misschien wat zwaar aangezet, maar er is geen andere direct van toepassing.

**Comment by BaDu-HSN** [comment]
Dit was in een van de hele druk perioden gisteren, ik vermoed dat de server (die de iconen genereert) heel even druk was met het serveren van een stuk of wat GE-netlaarten.
Graag in de gaten houden en hier melden indien dit vaker gebeurt

**Comment by BaDu-HSN** [comment]
Niet meer aangetroffen CLOSED
