### ISSUE TITLE
Lichte aanpassing begeleidende tekst feedbackformulier NL

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#167]
Slechts cosmetisch van aard. De begeleidende tekst kan net iets gevatter en rondom de zin die vertelt dat we niet op ieder commentaar persoonlijk kunnen reageren ook iets duidelijker. Nu staat er:

_Dank dat u wil helpen met het verbeteren van onze netkaart, vul alstublieft het formulier in.
Mochten wij naar aanleiding van uw bericht nog vragen hebben, dan nemen we contact met u op._

Verzoek is om dat te wijzigen in:

_Dank dat u wil helpen met het verbeteren van de netkaart. Via het onderstaande formulier kunt u een suggestie aandragen. 
We kunnen niet op ieder bericht persoonlijk reageren. Mochten we naar aanleiding van uw bericht nog vragen hebben, dan nemen we contact met u op via het ingegeven emailadres._

Ook de afsluitende tekst heeft een hikje. Als het formulier is verzonden, ziet men letterlijk:

_Dank voor uw feedback we gaan er zo snel mogelijk mee aan de slag_

Daar kan wel iets meer interpunctie in, dat lijkt wat professioneler. Verzoek is dan ook wijziging naar:

_Dank voor uw feedback. We gaan er zo snel mogelijk mee aan de slag. (U kunt indien gewenst de behandeling van het ticket volgen op Github.)_

Mogelijk dan met een link naar de correcte hoofdrepository op Github.

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#34
