### ISSUE TITLE
Vertalen van de webkaart

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#17]
Ondersteunde talen:
- NL
- DE
- UK
- FR

**Comment by BaDu-HSN** [comment]
De nieuwe balloons (balloon3.php) wordt vertaald (de begrippen).
Verdere vertaling van de hele kaart moet nog

**Comment by HansNien** [comment]
In aanvulling op een vraag op de vergadering en de app, welke beter via Github had kunnen worden gesteld. Is er een txt-bestand beschikbaar met de termen en woorden die vertaald moeten worden? Engels en Frans moeten nog, maar er is moeilijk zicht op welke woorden dat zijn.

**Comment by BaDu-HSN** [comment]
Het aantal woorden en termen breid zich vrijwel dagelijks uit.
Voorstel is eerst een taal af te werken (de.txt) en deze vervolgens te vertalen naar uk.txt en fr.txt

**Comment by BaDu-HSN** [comment]
Ook nog een vertaal functie maken voor javascript op basis van de.txt

**Comment by BaDu-HSN** [comment]
CLOSED
