### ISSUE TITLE
Google Maps stuk

### ISSUE THREAD

**Issue by coreice** [Hoogspanningsnet/Webkaart-scripts#170]
Gok dat je sleutel is verlopen of iets dergelijks?

> sb — js:35:336Google Maps API error: RefererNotAllowedMapError

![schermafbeelding 2017-08-01 om 20 52 39](https://user-images.githubusercontent.com/10442497/28841733-69ed5e12-76fb-11e7-9065-df625f3d13ce.png)

(Andere lagen werken prima)

**Comment by BaDu-HSN** [comment]
Ik had per ongeluk bij de verkeerde account van de API-console de restrictie gewijzigd om thuis een test machine te draaien.
De naam van de productie sleutel is nu gewijzigd zodat duidelijk is dat deze voor de productie omgeving is.
(idem voor de test-sleutel).

**Comment by BaDu-HSN** [comment]
FIXED and CLOSED
