### ISSUE TITLE
Verzoek om twee netvlakken reeds een zoomlevel hoger te tonen

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#172]
Verzoek om de netvlakken 72,6 - 123 kV (met het Franse 90 kV-net en 110 kV-netten) en 124 - 145 kV (met daarin het DK 132 kV net) alsnog te gaan tonen vanaf zoomlevel 9 in plaats van 10. 

Je weet hoe dat zit met mensen uit de 110 kV, die mopperen altijd dat ze zich genegeerd voelen. Maar los van die gekheid, er is er nu ook een nieuwe praktische reden verschenen die in Schleswig Holstein en ook in Denemarken opspeelt: de netdichtheid in minde bevolkte gebieden (Schleswig-Holstein) en de netdichtheid in gebieden met een goed ontwikkeld tussenspanningsnet. Dat laatste zien we op Lolland en Falster. Daar is een goed functionerend, vrij dicht 50 kV-net aanwezig waardoor 132 kV een echte koppelfunctie heeft en relatief dun gezaaid is. Daardoor verdwijnen deze verbindingen bij uitzoomen eigenlijk al van de kaart nog voordat je 'hoog' genoeg zit voor een proper overzicht. 

Zie het screenshot hieronder.

![110 en 132 te vroeg van de kaart](https://user-images.githubusercontent.com/23345566/28972416-e0482c32-792f-11e7-8d86-f43f553a9eef.JPG)

Ik meen me te herinneren dat de huidige keuze om 146 kV en hoger te hanteren als cut-off ooit zo is gegaan vanwege rendering en database m.b.t. de forse omvang van het Duitse 110 kV-net, maar is dat werkelijk zo'n groot punt dat het bezwaren of performanceproblemen oproept om de genoemde netvlakken reeds vanaf een niveau hoger te gaan tonen?

**Comment by BaDu-HSN** [comment]
De performance is niet een heel groot probleem vermoedelijk, de grootste performance problemen zitten bij GE-. Ik neem aan dat daar de zoom niveaus omgewijzigd blijven?

We hebben sowiezo nog iets te doen met de zoom-niveau's na inpassing van de Enexis data. De 10 en 20kV wordt mi wat te vroeg getoond (level 10) dit geeft een flinke server load aangezien de 10/20kV netten zeer dicht vermaasd zijn. een level van 14 of 15 zou veel beter zijn. Om toch hetzelfde aantal "cut-off's" te houden (waar ik zeer voor ben vanwege programmering) zouden we de grnes voor MV netten die nu op 30kV ligt kunnen verlagen naar bij 25kV. Hoe dit bij GE uitpakt heb ik nog niet onderzocht.
Dit heeft tot gevolg dat de 30kV gelijk met de 50kV getoond wordt, wat ook niet verkeerd is denk ik (het is veel meer een transport spanning dan een distributie spanning (zoal 10/20kV dat wel zijn). Dit betekend wel dat bij in BE waar veel 30kV aanwezig is de kaart wat zwaarder wordt.

**Comment by HansNien** [comment]
In GE zijn de zoomniveaus inderdaad reeds goed, alles wordt daar al vanaf iets grotere hoogte getoond (althans zo lijkt het) en met het oog op de toepassing van GE is het ook niet erg als die wat voller en drukker lijkt, Je kan daar tenslotte custom alle dingen aan en uit zetten, wat op de webkaart niet kan. Wat dit punt zelf betreft: als performance geen groot probleem is, dan zou ik de kwestie van 110- en 132 kV graag aangepast zien.

De kwestie met de lagere netten is interessant. Je hebt gelijk dat we die nu te vroeg tonen. Wat mij betreft heb je een goed idee te pakken met het anders leggen van de grens tussen tussenspanningen en de middenspanningsnetten. 30 kV een stukje opwaarderen qua "status" is in Nederland goed op zijn plek, vermits het in België niet de spuigaten uitloopt met serverload. Stel, je neemt 30 kV inderdaad samen met 50 kV en zet ze erin vanaf level 10 (huidig), 25/20 vanaf level 12 of 13 en dan 10 kV erin vanaf 14? Of levert dit juist een extra cut-off op? (Ik weet niet goed wat je daarmee bedoelt.) Als dat laatste het geval is, dan moeten we alles maar samen nemen onder 25 kV.

**Comment by BaDu-HSN** [comment]
> 25/20 vanaf level 12 of 13 en dan 10 kV erin vanaf 14? Of levert dit juist een extra cut-off op? (Ik weet niet goed wat je daarmee bedoelt.) Als dat laatste het geval is, dan moeten we alles maar samen nemen onder 25 kV.
Dat is inderdaad een extra cut-off, de 25kV staat me wel aan eigenlijk.

**Comment by HansNien** [comment]
Prima, duidelijk! Tot nader order gewoon samen nemen dan. Als het veel programmeerwerk scheelt moeten we gewoon eerst eens zien of het samengenomen ook goed werkt. (Mocht dan in de praktijk blijken dat het slecht werkt, dan kunnen we het wellicht alsnog heroverwegen.)

**Comment by HansNien** [comment]
Als aanvulling op de vraag waarmee dit issue werd gestart: op het piepkleine schermpje van een telefoon is de behoefte aan het eerder tonen van de twee genoemde netvlakken nog groter. Op Sjælland zien we bijvoorbeeld dat de 132 kV-dichtheid in het zuiden zo laag is dat we al aardig diep in moeten zoomen en dan nog steeds alleen de 400 kV-lijnen en de Kontekkabel zien. Dat maakt de bruikbaarheid kleiner, zie bijgesloten screenshot.

**Comment by HansNien** [comment]
Aanzet hiertoe is gemaakt in de nieuwe netkaartbijbel die over een paar dagen ter discussie wordt voorgelegd.

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#31
