### ISSUE TITLE
Verzoek om aanpassing eigenkleur netvlak 124-145 kV

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#173]
De concrete stap voortkomend uit de conclusie dat de huidige eigenkleur van met name de luchtlijnen van 132 kV best wel (____) combineren met zowel de luchtfoto als de Esri-dark achtergronden op de netkaart. In rood en groen ben ik een kneus, maar blauwzwart beheers ik wel en met een klein beetje hulp van een zeker persoon uit Zwolle hebben we een nieuw voorstel c.q. lichte tweak gedaan en getest in screenshots in Paint.

Verzoek tot aanpassing naar de volgende nieuwe kleur voor de volgende vier entiteiten:

124-145 kV luchtlijn: #2f3559
124-145 kV grondkabel: #509292
124-145 kV label: #304365
124-145 kV pictogram: #304365

**Comment by BaDu-HSN** [comment]
Benodigd is een aanpassing van stijlen.xml bij de net- en de webkaart.

**Comment by HansNien** [comment]
In elk geval wordt eerst de tabel in de Netkaartbijbel aangepast. Daarna, later deze week ofzo, loer ik eens in de genoemde bestanden.

**Comment by HansNien** [comment]
FIXED. Aan de hoofdcode zitten doe ik liever niet (en zeker niet als hot-line work), maar een paar hex-codes aanpassen in deze bestanden is wel te doen.
