### ISSUE TITLE
Voorstel voor aanpassing eigenkleur netvlak 7,3 - 12 kV

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#174]
Als antwoord op een opmerking in de app, voorstel tot lichte aanpassing van de eigenkleur van het netvlak waar 10 kV in valt. Die blijkt niet goed te zien te zijn op de luchtfoto's. Roestbruin op donkergroen is voor kleurenblinden ondoenlijk te beoordelen, dus ik heb deze even op de stoep van Ot gegooid. Die kwam met een iets lichtere variant die wat naar rood is opgeschoven.

Bedoeling is een iets betere zichtbaarheid van 10 kV op een lufo-achtergrond, maar tegelijk moet de kleur niet té dominant zijn om een '...holy shit, huuuuu peerd-ervaring' te voorkomen wanneer de zoomlevel van het zeer indrukwekkende 10 kV-net straks wordt bereikt, en verder moet hij niet zo dicht tegen 380/400 aan kruipen dat de kans op verwarring bestaat voor kleurenzieners.

Enfin, het verzoek tot aanpassing ziet er nu als volgt uit:

7,3 - 12 kV luchtlijn: #972f2f
7,3 - 12 kV grondkabel: #972f2f

Verder geen wijzigingen, de label- en pictogramkleur was immers al wat feller.

![aanpassing 10 kv](https://user-images.githubusercontent.com/23345566/29431648-f52ba232-8398-11e7-9e52-dbb96258ed20.png)

**Comment by BaDu-HSN** [comment]
Ziet er goed uit, ik ga er mee aan de gang, vereist aanpassing van stijlen.xml voor de webkaart en de netkaart.

**Comment by HansNien** [comment]
Als ie goed werkt (uiteraard bedoeld voor full-RGB mensen) neem ik 'm ook reverse op in de tabellen van de netkaartbijbel.

**Comment by HansNien** [comment]
FIXED. Aan grote stukken code zit ik liever niet, maar het aanpassen van wat hex-codes in beide stijlen.xml bestanden is wel te doen.
