### ISSUE TITLE
Aanpassen welkomstscherm met een accept/decline functie

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#176]
Sluit aan bij het andere issue over een gebruiksvoorwaardenpagina (zoals genoemd door Bas in de app) die ons houvast geeft om misbruik te voorkomen. Als er een gebruiksvoorwaardenpagina staat, moet het welkomstscherm iets worden aangepast zodat die pagina kan worden opgeroepen (een link die men kan aanklikken en die in een apart venster opent), maar ook met een accept- en een decline-knop. Accept verwijst dan rechtstreeks door naar de netkaart, decline kan terug verwijzen naar de mainsite van HoogspanningsNet. Of we bouwen er een andere custom pagina voor, dat moet nog maar besloten worden.

**Comment by BaDu-HSN** [comment]
Accept/Decline buttons met links daarachter is simpel te maken voor de webkaart, voor de netkaart moet ik er nog even naar kijken. Daar moet sowiezo nog een soort melding, welkomst en nieuwe zaken scherm komen.

**Comment by HansNien** [comment]
Bijgevoegd een mock-up van hoe de welkomstballon er bijvoorbeeld uit kan komen te zien als we een paar knoppen toevoegen. (Het keuzemenu met taal is overigens het hoofditem van issue #177)

![mock-up welkomstballon v7](https://user-images.githubusercontent.com/23345566/29584908-7e36519a-8785-11e7-971c-76c7ab5c4a8f.png)

**Comment by BaDu-HSN** [comment]
Ziet er wel maakbaar uit.
Incl de taal optie.

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#30
