### ISSUE TITLE
Welkomstballon in meerdere talen bieden

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#177]
Bij het maken van de mock-up voor de welkomstballon voor nieuwe gebruikers in gewijzigde vorm (met accept/decline knoppen m.b.t. de gebruikersvoorwaarden, zie naburig issue ook m.b.t. de CSS) kwam ik een probleem tegen. 

We hebben momenteel meerdere talen in de interface, maar niet in de welkomstballon en dat wordt een probleem als we in die ballon iets willen gaan opnemen over de gebruiksvoorwaarden. Wie geen Nederlands kan, kan heel leuk Duits of Deens aanklikken in de webkaart zelf, maar de welkomstballon is onleesbaar. Kunnen we daarom op de welkomstballon iets toevoegen waarin de gebruiker direct een soort functie 'choose language' heeft, waarna de welkomstballon na het maken van de keuze direct wordt ververst in de gekozen taal? En wat helemaal ideaal zou zijn, als de gebruiker daarna op akkoord klikt, dat de netkaartinterface dan meteen wordt geladen in de taal die in de welkomstballon al geselecteerd werd.

Default kan Nederlands blijven, we zijn tenslotte in beginsel Nederlandstalig.

(Uiteraard moeten de gebruiksvoorwaarden dan ook in meer talen, namelijk Nederland en Engels worden geboden, maar dat is een zaakje voor ondergetekende.)

![mock-up welkomstballon v7](https://user-images.githubusercontent.com/23345566/29584803-314c3318-8785-11e7-9fae-397584827d24.png)

**Comment by BaDu-HSN** [comment]
De taal keuze is denk ik geen groot probleem.
Het doorzetten naar de kaart taal vermoedelijk ook niet.

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#29
