### ISSUE TITLE
Na aanpassen interfacetaal gaat achtergrondkaart naar default

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#178]
Klein dingetje, misschien wel een wontfix, maar toch te melden.
Wie de achtergrondkaart heeft verzet van default Estri light naar een andere kaart en daarna de interfacetaal wijzigt, krijgt daarna weliswaar precies dezelfde view en kijkhoogte (netjes), maar de achtergrondkaart verandert dan terug naar Esri Light. Nu komt het weinig voor dat de interfacetaal tijdens gebruik een keer gewijzigd wordt, maar als bij switchen rekening kan worden gehouden met een reeds geselecteerde achtergrondkaart zou het gebruiksgemak en/of verzorgdheid toevoegen.

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#28
