### ISSUE TITLE
Veld Type (stationstype) wordt niet onthouden of weergegeven

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#179]
Het veld Type bij de categorie Hoogspanningsstation bevat een pulldownmenu waarin kan worden gekozen uit een discreet aantal opties. Nog niet aangeraakt is het veld leeg in versie 6.0 (er kan in V7.0 een default in, maar dat is een ander ding), maar eenmaal aangeraakt staat er bijvoorbeeld Trafostation, Converter of Klantstation. Echter, dit lijkt niet goed bewaard te blijven. Voor het Nederlandse 110 kV-gebied heb ik ooit alle stations eens van de correcte aanduiding voorzien, maar dat verdween na enige tijd vanzelf weer zodat het veld opnieuw leeg (alsof nooit aangeraakt) werd weergegeven. Een paar weken terug heb ik voor een stuk of tien stations rond de Drents-Overijsselse grens opnieuw alle types correct ingesteld en na een week of twee is de netkaart ze nu opnieuw allemaal vergeten. Dat lijkt op wat er de eerste keer ook gebeurde. Er zit dus een vreemde bug in dit veld.

**Comment by HansNien** [comment]
Dank voor het noteren als milestone. Een korte blik op de zaak toont dat deze bug nog steeds bestaat. Als kanarie in de kolenmijn gebruik ik al enige tijd station Veenoord, waar telkens Type wordt ingevuld. Aan de log is te zien dat deze schijnbaar elke paar weken zijn type-informatie is verloren. Geen dagelijks gebeuren, maar kennelijk om de paar weken. Totaal niet logisch. Geen idee wat die bug veroorzaakt.

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#27
