### ISSUE TITLE
Toevoegen link naar de Gebruiksvoorwaarden in het netkaartmenu aan de linkerzijde

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#180]
Zoals conform issue #175 is er een Gebruiksvoorwaardenpagina aangemaakt die overigens nog wel wat feedback kan gebruiken, maar dat is iets voor dat issue. Deze pagina is nodig wanneer we een keer een accept/decline invoeren, maar idealiter moet hij ook direct vanuit de netkaart op te vragen zijn.

De directe link is [http://www.hoogspanningsnet.com/netkaart/gebruiksvoorwaarden/](http://www.hoogspanningsnet.com/netkaart/gebruiksvoorwaarden/)

Verzoek is of deze in het snelmenu van de netkaart zelf ook oproepbaar kan zijn via een aanklikbare link, die een plek zou moeten hebben als vijfde van boven, tussen Release Notes en Disclaimer in. 
In de beschikbare talen wordt het woord als volgt:

_Gebruikersvoorwaarden_ (NL)
_Brugeraftale_ (DK)
_Nutzungsbedingungen_ (DE)
_User Agreement_ (EN)
_Wa'j d'r met mag_ (NDS) - alternatief kan ook _Bruuksveurwaorden_

**Comment by BaDu-HSN** [comment]
Wa'j d'r met mag (NDS) - alternatief kan ook Bruuksveurwaorden
Ik zou persoonlijk voor de laaste kiezen

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#26
