### ISSUE TITLE
PHP 7.1 is uit, kan de netkaart dat aan

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#181]
Zie ook het topic op het forum. PHP 7.1 is uit. Om herhaling van het probleem van vorige winter te voorkomen ga ik voorlopig nergens aan zitten zonder dat we nu eerst op voorhand weten dat de netkaart zich er niet in verslikt. Er is geen enkele haast bij, maar iemand met verstand van zaken (Bas, Mark) mag in een verloren uurtje graag eens onderzoeken of PHP 7.1 op een probleem voor de netkaart gaat stuiten bij doorvoering.

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#25
