### ISSUE TITLE
Tiling services willen soms niet goed laden

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#182]
Af en toe heeft de tiling service op de achtergrond de hik, met name als de netkaart wat langer achter elkaar gebruikt wordt. Bepaalde tegels weigeren dan te laden, ook na lange tijd. In- en uitzoomen verplaatst dat probleem slechts naar andere tegels in die zoomlevel. De zoomlevel zelf maakt verder niet uit, de achtergrondkaart zelf ook niet. Een paar minuten niets doen of de kaart opnieuw starten lost het vaak voor eventjes op, maar vroeg of laat komt het terug.
Ik dacht altijd dat het een lokaal probleem was in Holsloot (vanwege het trage internet daar), in Wageningen (vanwege mijn ouwe XP-bak daar) of op mijn telefoon (Android 4.5 Kitkat op een drieënhalf jaar oude Sonim A8+), maar toen we gisteren zowaar de netkaart een keer nodig hadden bij een studiegenoot elders in Wageningen die alles qua IT piekfijn op orde heeft, bleek het probleem ook daar te verschijnen.

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#24
