### ISSUE TITLE
Vlaamse vertaling maken en toevoegen

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#183]
Zoals we zien in de netkaartbijbel geraken we aan de grens wat met enig gewurm en geharrewar nog mogelijk is binnen de vertaling Nederlands. Het wordt ongemakkelijk.

Er zijn Belgische woorden die in de Nederlandse vertaling naadloos geadopteerd zijn (steeklijn), er zijn termen waarmee enigszins rekening wordt gehouden (dubbelvlagmast), maar er verschijnen ook steeds meer termen dankzij Bavo die zich er maar moeilijk in laten verwerken. Circuit of draadstel is eentje waar niet omheen te kletsen valt en die zich niet laat combineren. Ook caravellemast, hoogspanningspost- of cabine en een aantal termen in de omliggende documentatie (feedbackformulier) zijn enkele woorden anders. Als Nedersaksisch kan, dan kan Vlaams ook.

Ik ga Bavo vragen of hij het ziet zitten om een Vlaamse vertaling te maken in het standaardvlaams, niet in het Westvlaamse dialect.

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#23
