### ISSUE TITLE
Overkruisingshiërarchie bij plotten verbindingen klopt niet

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#184]
Het is op de netkaart het geval dat hogere netvlakken visueel over netten van een lagere orde heen worden getekend. Zo zal 380 kV altijd boven 150 kV worden weergegeven. Dat werkt inderdaad, maar de herhaalde onderverdeling van eerst alle luchtlijnen en dan alle grondkabels werkt niet. Zware grondkabels worden daardoor over lichtere luchtlijnen heen geprojecteerd. Ook binnen hetzelfde netvlak werkt het niet goed, waardoor een grondkabel van 110 kV soms over een luchtlijn heen wordt getekend op het overkruisingspunt. Zie de bijgesloten voorbeelden.
Geen groot probleem, maar toch een euvel.
![overkruisingshierarchie klopt niet](https://user-images.githubusercontent.com/23345566/31545171-96de2044-b01e-11e7-8f32-242e6714de11.JPG)

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#22
