### ISSUE TITLE
Blackman-afbeeldingen schrappen in versie 7 en vervangen door tekstje

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#185]
Zoals benoemd in de appgroep. Van de meeste objecten zoals buitenlandse grondkabels krijgen we nooit een foto en dat moet ook geen doel zijn, maar wel nemen de blackmans kostbare ruimte in die we met name op telefoonschermen wel beter kunnen gebruiken.

Wie het was weet ik niet meer, maar wel werd het argument geopperd dat de blackmans aanzetten tot het insturen van foto's om dat erdoor te zien is dat er eentje gewild is. Dat effect verdwijnt als we de blackmans helemaal schrappen, maar we kunnen een elegante middenweg bereiken door de afbeelding (een grote PNG) te vervangen door een geschreven regel tekst tussen vierkante haken: [geen foto beschikbaar]. Die neemt weinig ruimte in, maar vertelt precies hetzelfde.

**Comment by Knarvel** [comment]
Dat was ik. Mijn iudee was om in de blackman aktief naar fotoos te vragen, met ook een url naar een upload-pagina. Maar dat kan met een stukje text natuurlijk net zo goed grdaan worden.

**Comment by HansNien** [comment]
Mensen actief aanmoedigen tot het insturen van foto's, daar ben ik op mijn beurt een beetje huiverig voor. Het kan enorm uit de hand lopen qua aantal en qua werk dat we eraan gaan hebben (iedere foto moet gehost, gelinkt en gecontroleerd worden). We verliezen er ook een belangrijk deel van de controle mee op de bron van herkomst. Voordat er een aanmoedigingsbeleid komt denk ik dat we eerst eens een goede discussie hierover moeten hebben.

**Comment by BaDu-HSN** [comment]
Wat doen we er voor versie 7 mee?

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#21
