### ISSUE TITLE
Feedbackformulier voorzien van nieuw veld 'bron'

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#186]
Het feedbackformulier voorzien van een extra veld onder het bestaande open veld 'uw feedback' met de begeleidende tekst 'bron of referentie'.
Dat veld is optioneel, maar we moeten de tekst zo vormgeven dat het een verplicht nummer lijkt. Op zich mag men er alles in zetten, van URL tot een gedicht, maar het geeft misschien wat houvast waardoor mensen minder geneigd zijn om feedback aan te dragen dat voor ons op onze beurt niet te controleren valt vanwege gebrek aan referentie, zeker als bij het emailadres een dummy wordt ingevuld.

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#20
