### ISSUE TITLE
Inloggen voor editten in webkaart eenvoudiger maken

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#187]
Op dit moment zit er in het inloggen voor wijzigingen wat vreemds in de webkaart (maar ook de GE-kaart). Je klikt op de tekst "Verbindingen", dan verschijnt een nieuwe sidebar met de ruwe data en een inlogknop, na inloggen kan je de data wijzigen in het wijzigingsdeel (als je eenmaal ingelogged bent, ga je direct naar het wijzigingsdeel) 

Wat ik voorstel is : 
- Onder in de topbar een user inlog-icoon te maken
![afbeelding](https://user-images.githubusercontent.com/21307438/33200914-c82c2b0c-d0f6-11e7-9c6c-9b34f8b8f2d6.png)
- Daarop opent het inlog scherm in de sidebar
![afbeelding](https://user-images.githubusercontent.com/21307438/33200930-dda41634-d0f6-11e7-8601-25c189c9c81c.png)
- Na inloggen komt in de topbar de gebruikersnaam te staan
![afbeelding](https://user-images.githubusercontent.com/21307438/33200946-f66a497c-d0f6-11e7-84a6-e50caa168376.png)
- Na inloggen wordt de edit-link in de sidebar (klikken op het type) actief
![afbeelding](https://user-images.githubusercontent.com/21307438/33201019-259b245a-d0f7-11e7-81a4-ae5b8bf0a585.png)
- Na het klikken op het type van de het item in de sidebar opent de wijzigingen-sidebar van het item.
![afbeelding](https://user-images.githubusercontent.com/21307438/33201041-38d22690-d0f7-11e7-9eb9-47d727869652.png)
- Het ruwe weergave scherm is niet meer nodig
![afbeelding](https://user-images.githubusercontent.com/21307438/33201146-a294d32a-d0f7-11e7-9efd-e5526eb2aa66.png)
- De weergave van de versie verdwijnt (deze voegt weinig toe, de gebruiker heeft toch geen keuze), zie ook issue https://github.com/Hoogspanningsnet/Webkaart-scripts/issues/188

Voordelen:
- De normale gebruiker wordt niet lastig gevallen met de ruwe data als hij per ongeluk op de type-tekst klikt.
- We zijn toekomst vaster wanneer we ervoor kiezen een deel van onze services alleen aan te bieden aan geregistreerde gebruikers (er is immers al een inlogmechanisme).
- Meer consistentie (voor versie weergave) met de GE-kaart

**Comment by Knarvel** [comment]
Ik gebruik lastpass op mijn computer, en heb daardoor voor de netkaart geen inlog-sores. Helaas werkt dat bij GE niet, omdat onder de motorkap voor het scherm met de wijzigingen steeds een andere URL toegepast wordt.

**Comment by HansNien** [comment]
Dit komt als een donderslag bij heldere hemel, en dan zijn de stormchasers altijd hoogst verbaasd en verblijd. Dit ziet er efficiënt en begerenswaardig uit. Het zou een wezenlijke toevoeging zijn in de workflow.

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#19
