### ISSUE TITLE
Versie en colofon weergave van webkaart veranderen

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#188]
De versie wordt nu rechtsboven weergegeven, maar heeft beperkte toegevoegd waarde. In issue https://github.com/Hoogspanningsnet/Webkaart-scripts/issues/187 wordt deze daarom vervangen door een inlog icoon. Verder ontbeert de webkaart een soort colofon windowtje.

Om de versie informatie wel zichtbaar te maken stel ik het volgende voor:
- De versie weergave moet onder "About" onder het instellingen zichtbaar gemaakt kunnen worden.
![afbeelding](https://user-images.githubusercontent.com/21307438/33201238-ee6d9926-d0f7-11e7-9e1e-8b68970beb1c.png)
- Daarnaast ook bij klikken op de tekst in de topbar "HoogspanningsNet Netkaart"
![afbeelding](https://user-images.githubusercontent.com/21307438/33201530-3a3e5826-d0f9-11e7-8e94-f230e16c3f02.png)
- Waarna een schermpje weergegeven wordt analoog aan het balloon in de GE-kaart (denk ook aan de vertaling?). 
![afbeelding](https://user-images.githubusercontent.com/21307438/33201307-3bc3858c-d0f8-11e7-8ae5-96d3eda94faf.png)

**Comment by HansNien** [comment]
Mee eens, klinkt goed (en ruimtebesparend). Houdt overigens ook enig verband met #180.

**Comment by Knarvel** [comment]
Ook mee eens

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#18
