### ISSUE TITLE
Naamsvermelding fotograaf van fotoos

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#189]
De CC-licentie BY schrijft een naamsvermelding van de fotograaf van gebruikte fotoos voor. (ik denk hierbij aan fotoos van div. wiki's vooral uit het buitenlands) Daarom zou ik graag een extra veld in de objekten die een foto kunnen voeren willen voorstellen waar deze naam ingevuld kan worden. Ideaal zou het zijn dat dit veld direkt onder de foto wordt weergegeven en onderdrukt wordt als er niets instaat.

**Comment by HansNien** [comment]
Bedoel je ongeveer zoiets? Kleiner font, alleen weergeven indien ingevuld en indien foto er nog staat? (Dus dat het niet blijft staan als bijvoorbeeld het fotoveld weer leeg is gehaald?)

![concept fotonaam weergeven](https://user-images.githubusercontent.com/23345566/33212805-f9757ffa-d124-11e7-93ae-145c34f29100.jpg)

**Comment by BaDu-HSN** [comment]
Inderdaad zoiets is prima.
(Issue graag open laten staan)

**Comment by HansNien** [comment]
Oeps, verkeerde knop gebruikt. Open laten staan was inderdaad de bedoeling.

**Comment by Knarvel** [comment]
Ja, mooi. Dit bedoelde ik.

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#17
