### ISSUE TITLE
Lettertype bij Loginscherm wijkt af van CSS balloons

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#19]
De voortgaande link en het inlogscherm voor editors via de ballon worden weergegeven in Times new Roman en niet door de CSS van de ballon gestyled. Het scherm 'login to edit' en het inlogscherm kan echter wel "per ongeluk" door alle users gezien kan worden. Niet heel boeiend, het viel me slechts op.

**Comment by BaDu-HSN** [comment]
Inderdaad ee  Must Have
Eigenlijk zou ik van het tussenscherm af willen, klikken op de editlink brengt je naar het editscherm of het tussenliggende inlogscherm. Scheelt een stap bij eerste inlog. 
Verder zou ik de ID niet meer willen tonen in de balloons (de normale gebruiker heeft er weinig aan, e het schept weer wat ruimte), de edit link kan dan onder de Naam geplaatst worden.
Verder : lettertype aanpassen is zo gedaan (deze schermen achter de balloon maken geen gebruik van CSS)
Is dit akkoord zo?

**Comment by BaDu-HSN** [comment]
FIXED
Alle lettertypen naar Arial aangepast
