### ISSUE TITLE
UTF-8 als tekenset gebruiken

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#190]
Zodat we ook oost europese talen enz kunnen ondersteunen

**Comment by BaDu-HSN** [comment]
Zie ook:
https://stackoverflow.com/questions/37906212/mysql-which-default-collation-should-i-set-to-cover-all-european-characters

**Comment by HansNien** [comment]
Dat zal in de netkaartbijbel moeten worden verdisconteerd als blijkt dat dit haalbaar is. Dat we het nodig gaan hebben blijkt al een beetje nu de grens met Polen en Slovenië wordt genaderd. (In Scandinavië heb ik vooralsnog geen problemen.)

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#16
