### ISSUE TITLE
Ballon in webkaart verdwijnt al bij muis schuiven over andere entiteit

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#20]
Bij het aanklikken van een entiteit verschijnt netjes de ballon, maar wanneer je in een drukke omgeving met veel andere entiteiten vlakbij (rij masten, parallelle straat masten) al reeds een hover boven een andere entiteit maakt, verdwijnt de ballon al. Dat is misschien wat snel. Ballon pas weer weg bij klik of tik náást de ballon (zoals in de GE-interface) is m.i. handiger, maar het kan zijn dat anderen dat anders zien.

**Comment by coreice** [comment]
Het zal inderdaad persoonlijke voorkeur zijn, al kan het wel handig zijn om "de bediening" zoveel mogelijk uniform te houden op alle platformen (Webkaart desktop, webkaart mobiel, GE-kaart). Dat de ballon pas weggaat als je van de ballon _wegklikt_ op de webkaart lijkt mij persoonlijk ook wel handiger en ook in lijn met zoals het elders werkt.

**Comment by BaDu-HSN** [comment]
Akkoord =>  Must Have

**Comment by BaDu-HSN** [comment]
FIXED
De balloons sluiten nu alleen na het klikken op de de close button in de rechterboven hoek of door ergens naast de balloon te klikken op de kaart. Na een pan of zoom actie en bijgevolg veranderen van de kaartinformatie blijft de balloon geopend.
