### ISSUE TITLE
Kiezen van tiling service via instellingen menu

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#22]
Het opnemen van een extra knop heeft niet veel nut als we ook een instellingen menu hebben.
Wat mij betreft kan dit worden doorgevoerd, akkoord?

**Comment by HansNien** [comment]
Akkoord, helemaal mee eens. Een simpel menuknopje met een tandwieltje is tegenwoordig standaard en genoegzaam bekend geraakt bij apps en webapplicaties, men weet dat daar de instellingen onder zitten.

**Comment by BaDu-HSN** [comment]
FIXED
Opgenomen in de sidebar Instellingen:
![image](https://cloud.githubusercontent.com/assets/21307438/20495459/74041cd4-b021-11e6-9682-5ffa0a02b226.png)
