### ISSUE TITLE
Lichte vergroting pictogrammen (en eventueel label) bij mouseover

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#23]
Conform terecht comment in/op de netkaartbijbel editie III. In de interface van Google Earth wordt een label, pictogram of icoon een fractie groter als men de muis of de vinger erop zet. Dat is handig om te kunnen zien of je wel de goede aanklikt of tikt voor meer informatie wanneer er veel entiteiten op een kluitje zitten (mastbolletjes). Een dergelijke functie is niet aanwezig in de webkaart in wording, maar kan wel handig zijn.

**Comment by BaDu-HSN** [comment]
Dit is wellicht oplosbaar middels CSS onhover functie

**Comment by BaDu-HSN** [comment]
FIXED
Iconen en labels worden (onafhankelijk van elkaar) 20% groter
