### ISSUE TITLE
Label bij iconen weergeven

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#24]
We hebben nu een popup bij hover over (ook een tooltip tekst).
In V1.0 van Leaflet hebben we een tooltip welke gestyled kan worden en permanent weergegeven.
http://leafletjs.com/reference-1.0.0.html#tooltip-option
(afhankelijk van issue https://github.com/Hoogspanningsnet/Webkaart-scripts/issues/25)

**Comment by HansNien** [comment]
Meerwaarde van permanent getoonde namen is dat mensen die de weg niet uit het hoofd kennen op de netkaart. Anders blijf je schuiven met de muis en in jezelf mopperen 'grrr, waar ligt Wijgmaal ook alweer' of soortgelijk. Styling is wel gewenst.

**Comment by BaDu-HSN** [comment]
OK, gaan we maken.
CSS:
......:hover {
  font-size: 1.1em;
}

**Comment by BaDu-HSN** [comment]
Fixed
Styling blijft nog even op de lijst staan in een nieuw issue (https://github.com/Hoogspanningsnet/Webkaart-scripts/issues/33)
