### ISSUE TITLE
Feedbackformulier met objectnummer

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#26]
Zoals genoemd in de nieuwe netkaartbijbel.
Het implementeren van een feedbackformulier. In de webkaart vlot te bereiken vanaf bijvoorbeeld het snelmenu _Instellingen_ zoals gesuggereerd in een ander ticket, of mogelijk zelfs tevens direct vanaf de ballon. Handigheid zou zijn dat bij gebruik vanaf de ballon het objectnummer dan meteen kan worden toegevoegd, voor het geval van opmerkingen of commentaar op reeds bestaande objecten. Dat vereist ook weer een zoekfunctie voor de beheerders zodat direct de entiteit in kwestie numeriek kan worden ingeklopt en wordt weergegeven, zodat de beheerder dan direct weet om welk object het gaat.
Dit is een behoorlijk complexe functie met programmeer- en designwerk, achterliggende procesgang (hoe en wie behandelt formulieren) en echter een betrekkelijk lage prioriteit omdat het niet tot de primaire functionaliteit behoort. De couldhave-status is hier op zijn plek.

**Comment by BaDu-HSN** [comment]
Dit kan op meerdere manaieren opgelost worden qua procesgang:
- Een mail sturen naar een nog in te bedenken adres(sen), nadeel is dan dat we niet centraal kunnen bijhouden wat de wijzigingen zijn en wie ze heeft gedaan of wie de betreffende wijziging opppakt.
- Een issue openen op Github onder een Netkaart repository, de beheerders kunnen daar bij houden wie het issue gaat verwerken enz (analoog aan deze script-issues). Nadeel is wel dat alle beheerders zich moeten melden op Github.
- Een aparte tabel in de database maken waar de issues in geplaatst worden, en die vervolgens weergegeven wordt op de beheerderspagina van de netkaart. Hier kunnen beheerders dan kijken wat de nieuwe issues zijn en ze gaan behandelen. Nadeel is een boel programmeerwerk.

Ik persoonlijk voel het meeste voor Github

**Comment by coreice** [comment]
Github lijkt mij voor deze taak het meest handig. Je zou nog andere (bug)trackers kunnen overwegen (Mantis, JIRA...) maar dat zorgt ook weer voor het nodige gedoe (weer een ander platform wat je in de gaten moet houden etc. etc.).

**Comment by BaDu-HSN** [comment]
Github it is then, we hebben er al een plek voor : https://github.com/Hoogspanningsnet/Netkaart

**Comment by BaDu-HSN** [comment]
Niet vergeten dit ook voor de GE-implementatie te doen (issue

**Comment by BaDu-HSN** [comment]
Zie 
https://github.com/ornicar/php-github-api#open-a-new-issue
voor een api

**Comment by BaDu-HSN** [comment]
CLOSED
Maak voor bugs en kleine wijzigingen een nieuw issue aan.
