### ISSUE TITLE
Open velden en gesloten velden met een pulldownmenu

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#27]
Conform een streven in de netkaartbijbel.
Open en gesloten velden bij het invoeren van informatie kunnen duidelijkheid scheppen, een wildgroei aan eigen notitiewijzen voorkomen en dergelijke velden kunnen later ook _querybaar_ zijn vanwege hun uniformiteit, mogelijk iets voor toekomstige toepassingen waar nu nog geen zicht op is.
Een open veld staat het toe om alles in te voeren, een gesloten veld staat het toe om alleen een getal in te voeren of een discrete keuze te maken uit een pulldown-menu. Voor discrete keuzes (systeem, verbindingstype, etc.) werkt dit duidelijker en overzichtelijker bij het invoeren van informatie.

**Comment by BaDu-HSN** [comment]
CLOSED (Duplicate from https://github.com/Hoogspanningsnet/Webkaart-scripts/issues/37)
