### ISSUE TITLE
Meertaligheid

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#28]
Parapluticket voor het hele subproject van meertaligheid, zodat er tenminste eentje voor is.
Het hele idee van vertalingen en/of om de kaart te kunnen tonen in een andere gekozen taal zoals Engels, Duits en Frans (en in tweede instantie Deens, Nedersaksisch, Vlaams, Fries, wat dies meer zij). Meertaligheid is groot en complex, niet direct noodzakelijk voor de functionaliteit van dit moment en relatief laag op de prioriteitenladder. Een typisch enhancement voor versies hoger dan V6.

**Comment by BaDu-HSN** [comment]
CLOSED (Duplicate with https://github.com/Hoogspanningsnet/Webkaart-scripts/issues/17)
