### ISSUE TITLE
Straal range automatisch circuits aan mastpositie toekennen geeft problemen

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#29]
Momenteel wordt met een script rondom de mastpositie heen gekeken welke circuits daar in de buurt zijn, zodat deze automatisch worden toegekend aan de mastpositie. Dit werkt bijna overal goed, maar bij sommige combilijnen en portaalstraten zijn de circuits te ver weg vanuit de mastpositie om opgepakt te worden (vb. enkele posities in ZL-MEE, portaalstraat Harculo, etc.). Elders bij een overkruising wordt een circuit 'per ongeluk' juist wel opgepakt (vb. Sekdoorn, Welsumerveld, etc.) 
Hier is geen concrete oplossing voor denkbaar zonder het ene probleem op te lossen waarbij het tegenovergestelde probleem juist in de hand wordt gewerkt. Enige wat ik kan bedenken is een soort functie waarbij bijvoorbeeld default 20 meter om de mastpositie heen wordt gekeken, maar er in de editorfunctie in de ballon ook tot bijvoorbeeld 100 meter om de mast heen wordt, waarna de editor (bij moeilijke gevallen) handmatig de circuits die betrekking hebben zou kunnen aanvinken of uitvinken om zo alsnog de correcte situatie te bereiken. Maar dit zal ongetwijfeld razend ingewikkeld zijn.

**Comment by BaDu-HSN** [comment]
Ingewikkeld inderdaad, het is misschien makkelijker om gewoon de juiste lijnnamaen in het editor scherm in te vullen. Het weergave script kijkt dan of dit veld gevuld is in de database in, indien ja neemt het die waarde over, indien nee berekend het de circuits op de automatische wijze.

Het enige nadeel wat je dan hebt is dat wanneer we de lijnnamen wijzigen we dat ook in de betreffende masten moeten aanpassen, maar zou in principe wel makkelijk te achterhalen moeten zijn.

Is dit een werkbaar systeeem?

**Comment by HansNien** [comment]
Op zich klinkt het idee met de lijn-ID's werkbaar.
Als er default wordt gehengeld in een straal van twintig meter om het mastbolletje heen gaat het in 95% van de gevallen reeds prima, dus een automatisch systeem verdient wel de voorkeur. Stel, is er iets te bouwen dat in eerste instantie de huidige wijze gebruikt (automatisch hengelen op ID, want in 95% van de gevallen correct), maar dat ook in staat is om -indien de situatie erom vraagt- handmatig overruled te kunnen worden door bij de mastpositie in kwestie een ontbrekend ID extra te kunnen toevoegen of er juist een te kunnen verwijderen?

**Comment by BaDu-HSN** [comment]
Dat laatste is geen probleem in het circuit veld kan dan ingevuld worden:
v1000,v1001,v2002,v2003

Het script maakt daar dan van:
380kV vanHot-Naarher (zwart)<br>
380kV vanHot-Naarher (wit)<br>
110kV vanHaver-toGort (bruin)<br>
110kV vanNijverdal-totLettele (geel)<br>

**Comment by HansNien** [comment]
Hoe werkt dit onder de klep? Doorloopt een mastbolletje bij de creatie (maanden terug) éénmaal het proces van twintig meter eromheen loeren, dan de circuits plotten en vervolgens de situatie als harde eigenschappen toevoegen aan de mastpositie? Als die manier gebruikt wordt, dan ontstaan er geen problemen als er aan die informatie handmatig iets gewijzigd wordt en dan is de aangedragen manier die je hierboven schetst m.i. uitstekend om het probleem op te lossen.

**Comment by BaDu-HSN** [comment]
Nee the magic happens tijdens het genereren van de ballon van de aangeklikte mast:
Het script doet een query op de tabel van de verbindingen waarbij er virtueel een vierkantje om de mast getekend wordt, van alle verbindingen die luchtlijnen zijn en het vierkantje kruisen wordt de naam geselecteerd en vervolgens in het circuits veld van de balloon weergegeven. 
Alles on the fly dus.
Voor de volledigheid hierbij de query:
```
	SET @Meters_Offset = ".strval($MastLijnAfstand);
	SET @offy = @Meters_Offset / 111248;
	SET @offx = @Meters_Offset / 73500; 
	SELECT Spanning, Naam from Verbindingen Where HoofdType='Lijn' AND ST_Intersects(linestring, Linestring(
                POINT(".$rij['lon']."-@offx, ".$rij['lat']."+@offy), 
		POINT(".$rij['lon']."-@offx, ".$rij['lat']."-@offy), 
		POINT(".$rij['lon']."+@offx, ".$rij['lat']."-@offy), 
		POINT(".$rij['lon']."+@offx, ".$rij['lat']."+@offy), 
		POINT(".$rij['lon']."-@offx, ".$rij['lat']."+@offy))) ORDER BY Spanning DESC, Naam ASC
```

Dat dus

**Comment by HansNien** [comment]
Aha, dus toch on the fly. Ik heb maar zes studiepunten besteed aan daadwerkelijk codekloppen (weliswaar Python, maar toch). Dat is genoeg om de query te kunnen volgen, maar ik kan ze zelf niet bouwen. 
Dat ze aanpassingen doen wel lastiger, want je krijgt dan objecten waarvan een deel dynamisch bij elkaar wordt geraapt terwijl een geforceerde aanpassing slechts eenmalig gedaan word door een beheerder en er dan altijd ook bij moet worden opgediept. Die mastposities worden er niet makkelijker op...

**Comment by coreice** [comment]
Denk dat het met de complexiteit wel meevalt als je controleert bij het ophalen van de informatie, of er handmatig ingevoerde data aanwezig is. Simpel if/else dus.

Is het een idee om de bedrijfszekerheid van de circuitchecker wat te verhogen als je het laat controleren op spanning? Als ik het goed zie, is voor zowel de mast als bij het circuit de spanning opgegeven. Als deze gelijk zijn aan elkaar zou je in sommige situaties* kunnen concluderen dat je de goeie te pakken hebt.

* Bij een kruising van bijvoorbeeld een 380 en een 150 kV lijn.

Voor complexere situaties zouden wellicht ook checks te bedenken zijn, maar de moeite is wellicht niet in verhouding ten opzichte van de mate waarin het probleem voorkomt.

**Comment by BaDu-HSN** [comment]
Je suggestie is ok, meer werkt niet bij meerdere spanning aan een mast (net een situatie waarbij we zoms een lijn missen omdat ie te ver weg ligt) Ik sluit me daarom (bij gebrek aan een duidelijke set met regels (die vrijwel niet is op te stellen)) aan bij jouw laatste zin Mark.

**Comment by BaDu-HSN** [comment]
FIXED in balloon2.php op de testserver.

                        $delimiters = ' .,;-|\\/';
			$lijnen = rtrim($rij['Circuits'], $delimiters);
			$delimiters = str_split($delimiters);
			$lijnen = str_replace($delimiters,', ',$lijnen);
			$lijnen = str_replace('v','',$lijnen);
			$query	= "SELECT Naam from Verbindingen WHERE ID IN (".$lijnen.") ORDER BY Spanning DESC, Naam ASC";
			$gegevens = mysqli_query($connection, $query);
			$temp = '';
			while($verbing = mysqli_fetch_array($gegevens)) {
				$temp = $temp . $verbing['Naam'] . "<br>";
			}
			echo '<div class="gegtitel">'.vertaal("Circuits").'</div><div class="gegwaarde">'.$temp.'</div>';

LET OP: 
- Gebruik een van de volgende tekens als koppelteken :  .,;-|\/<spatie>
- ID's mogen met of zonder "v" (moeten natuurlijk wel verbindingen zijn)
