### ISSUE TITLE
portable netvieuw

### ISSUE THREAD

**Issue by Knarvel** [Hoogspanningsnet/Webkaart-scripts#3]
Oude wens:
Bij een draagbaar apparaat de kaart automatisch de kaaart laten volgen...
Dit graag ook afschakelbaar ivm battery-life issues

**Comment by BaDu-HSN** [comment]
https://www.domoritz.de/leaflet-locatecontrol/demo/

**Comment by BaDu-HSN** [comment]
Inmiddels zit de locate funcite er in (eenmalig gaan naar locatie).
Via het instellingenscherm kan straks kiezen voor eenmalige update of continue.
Zie ook issue over slidebar: 
https://github.com/Hoogspanningsnet/Webkaart-scripts/issues/16
