### ISSUE TITLE
Legenda via een button

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#30]
![netkaart op telefoon schets](https://cloud.githubusercontent.com/assets/23345566/20306878/079060aa-ab3d-11e6-95d4-fcfc2e8b8a67.png)

De webkaart in ontwikkeling wordt reeds veel op kleine schermpjes gebruikt waarbij het onwenselijk is om de huidige legenda (een transparante en enigszins verouderde PNG-afbeelding) permanent te tonen. Een oproepbare legenda met CSS-styling die via een discreet maar duidelijk knopje kan worden opgeroepen is dan te prefereren. De netkaart is een kleurencircus en heeft een zeker kennisniveau nodig voordat men hem een beetje snapt (nieuwe gebruikers), dus een legenda die vlot en duidelijk in de applicatie zelf oproepbaar is, is beter dan een link naar een externe plek met nadere verklaring ergens op de mainsite in een nieuw venster. Het gaat in eerste instantie vooral om de techniek. Het werken aan de bijbehorende layout en de icoontjes vereist overleg en een aanvraag richting Zwolle (actiepunt HN) en is een tweede prioriteit. Wanneer de legenda samen met enkele andere zaken (links naar disclaimer, formulier, uitgebreide documentatie) bijvoorbeeld onder een aparte menuknop terecht zou kunnen komen, dan kan het geheel er op een telefoon discreet uit blijven zien en toch met één druk op de knop oproepbaar zijn. Zie het bijgesloten screenshot/mock-up voor een indicatie.

**Comment by BaDu-HSN** [comment]
Legenda en bijbehorende knop is aangebracht.
Heb nu het legenda plaatje van de normale netkaart gebruikt, die niet echt mooi is.
Ot moet aan het werk :)

**Comment by BaDu-HSN** [comment]
Voor de legend figuur is een apart issue aangemaakt (https://github.com/Hoogspanningsnet/Webkaart-scripts/issues/39)
