### ISSUE TITLE
Toevoegen subgroep Supergeleidende kabels in Verbindingen

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#31]
Conform de visie in de netkaartbijbel. Naast de groep Luchtlijn, Grondkabel en Onderwaterkabel is een Supergeleidende kabel ook een groep op zichzelf waard vanwege de afwijkende constructie- en bedrijfseigenschappen. Kleine enhancement.

**Comment by BaDu-HSN** [comment]
CLOSED (Duplicate van https://github.com/Hoogspanningsnet/Webkaart-scripts/issues/34)
