### ISSUE TITLE
Bij inloggen via ballon of backend link 'terug' opnemen bij foute invoer

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#32]
Oeps, zojuist voor het eerst waarschijnlijk een typo gemaakt bij het inkloppen van gebruikersnaam of wachtwoord bij inloggen via de tekstballon... 
Er blijkt dan de tekst _User/Password Invalid_ te verschijnen, maar geen knop met 'terug' of iets in die trant. Hoewel even naast de ballon klikken het probleem ook oplost, is het wellicht eleganter om een linkje op te nemen met 'terug' o.i.d.

**Comment by BaDu-HSN** [comment]
FIXED

added:
  echo '<p>Click <a href="loginedit.php">here</a> to try again.';
