### ISSUE TITLE
Toevoegen velden in de ballonnen Verbindingen

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#34]
Conform suggestie in de bijbel om er een Github van te maken voor versie 6. Concreet als we de bijbel (zoals het er nu voor staat) volgen en het mogelijk blijkt om een pulldownmenu met discrete keuzes te realiseren. Bij Verbindingen zijn er drie dingen die nu in de bijbel een pulldown en in het geval van Netfrequentie een open veld zouden kunnen hebben.

**Pulldown met Constructiewijze:**
- Luchtlijn (default indien niets gekozen)
- Grondkabel
- Onderwaterkabel
- Supergeleidende kabel

**Pulldown met Systeem:**
- AC Driefasen (default indien niets gekozen)
- AC Tweefasen
- AC Fase-nul
- DC Monopole Earth return
- DC Monopole Metallic return
- DC Symmetrical Monopole
- DC Bipole
- anders/onbekend

**Netfrequentie:**
Voert standaard de waarde 50 (default indien niets gewijzigd). Het veld mag de postfix _Hz_ automatisch toevoegen. Het veld zou overschreven moeten kunnen worden met willekeurig iedere andere waarde, zoals 16,7 of 60. Voor DC is het getal 0 niet elegant. Bij DC is het voorstel om bijvoorbeeld de waarde 0 te kiezen (of 9999), waarna het veld in de frontend van de ballon wordt verborgen.

**Comment by BaDu-HSN** [comment]
Akkoord => Enhancement

**Comment by HansNien** [comment]
Zie inmiddels ook #37 , waarin alles uitgebreider staat. Deze kan wellicht gesloten worden, behalve dat de informatie die erin staat over netfrequentie nog relevant is.

**Comment by BaDu-HSN** [comment]
CLOSED (Duplicate met https://github.com/Hoogspanningsnet/Webkaart-scripts/issues/37)
