### ISSUE TITLE
Toevoegen velden in ballonnen Mastposities

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#35]
Conform een voorstel met enkele comments in de bijbel, bedoeld voor release 6.
Toevoegen van twee velden Mastmodel en Subtype. Hier geclassificeerd als musthave, als is enhancement misschien ook goed omdat het geen essentiële onmisbare functionaliteit is. 

Mastmodel is er al, maar in een nieuwe opzet kan het een pulldownmenu zijn met discrete opties die het HSN-HNM Mastclassificatiemodel volgen, zie [http://www.hoogspanningsnet.com/mastsoortenclassificatie/mastclassificatiemodel/]. Subtype is opzettelijk een open veld waarin de pylon geeks tot het draadje kunnen gaan, zoals IJsselmij hamerkop generatie I, S+2.

**Comment by BaDu-HSN** [comment]
Akkoord => Enhancement

**Comment by HansNien** [comment]
Gesloten, want ingebed en meegenomen in combinatieticket #37
