### ISSUE TITLE
Veld met ontwerpspanning in verbindingsballon verbergen indien niet ingevuld

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#36]
Kwam zomaar voor de dag. Bij aanklikken van de ballon van een verbinding zien we de velden Bedrijfsspanning en Ontwerpspanning. Aangezien bijna alle verbindingen op hun nominale ontwerpspanning worden bedreven, is het eigenlijk onzin om het veld Ontwerpspanning weer te geven in het geval deze gelijk is aan de bedrijfsspanning. Zeker als je bedenkt dat er default 0 kV staat, wat zelfs echt onjuist is.
Voorstel is om het veld Ontwerpspanning te verbergen indien deze leeg is gelaten. (Bij subnominaal bedreven verbindingen kan dan iets worden ingevuld en plopt ie vanzelf in beeld in de ballon, bij nominaal bedreven verbindingen blijft ie dan weg en dat scheelt kostbare ruimte en een (lelijk) leeg veld.

**Comment by BaDu-HSN** [comment]
Akkoord => Must have

**Comment by HansNien** [comment]
Wat betreft velden die altijd getoond, indien ingevuld getoond en altijd verborgen op de frontend moeten zijn, ik maak een apart ticket aan om vervuiling van dit exemplaar te voorkomen.

**Comment by HansNien** [comment]
Gesloten, want opgevolgd en opgenomen in topic #37
