### ISSUE TITLE
Toe te voegen velden en entiteitengroepen m.b.t. de ballonnen

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#37]
Groot item. Ik heb een en ander uit de bijbel en de aangedragen comments opgediept en er een document van geprobeerd te maken. Hoewel ik heb geprobeerd zo intelligent mogelijk om te gaan met de verschillende velden en hoe die te gebruiken, gaat er gaat waarschijnlijk erg veel werk in zitten en zijn er vast een aantal dingen waarvan iemand anders een goed idee heeft over hoe het handiger kan. 
Ik zet hem voorlopig op Enhancement en Musthave, maar binnen dit onderwerp is het best mogelijk dat sommige subonderdelen niet mogelijk zijn of een andere status zouden moeten krijgen. Mogelijk is dit de hoofdprijs van release 6. (De andere twee tickets kunnen gesloten worden, want die zijn bij dezen vervangen door dit exemplaar.)

[http://www.hoogspanningsnet.com/wp-content/uploads/Ballonnentabel.xls]

Edit: omdat Github blijkbaar geen xls-bestand meer aanneemt en ik hier nu eenmaal met Office 2003 zit, bij dezen de link naar het bestand. Dan maar even hosten op de server van de mainsite. Voor elke weg is een omweg. ;-)

**Comment by BaDu-HSN** [comment]
De input velden moeten nog gedaan worden in de edititem.php

**Comment by BaDu-HSN** [comment]
Masten in edit schermen zijn gedaan.

**Comment by BaDu-HSN** [comment]
Allen balloons gedaan
