### ISSUE TITLE
Searchbox en results kleiner maken

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#38]
Nu lopen ze op kleine mobile dvises over de scherm rand
(media tag gebruiken?)
De grootte van het control is ook niet in lijn met de rest van de controls (mag flink kleiner)

**Comment by BaDu-HSN** [comment]
Control grootte is nu redelijk in lijn met de overige controls.
De breedte is 100pixels kleiner gemaakt
Maar nog steeds een beetje te breed, misschien de knoppen (vergrootglas en kruis) naar links halen?

**Comment by HansNien** [comment]
@BaDu-HSN Op een desktop is het knopformaat uitstekend (en misschien moet het daar juist niet kleiner dan nu, omdat de controls anders niet opvallen). Op een telefoon is het ook uitstekend, daar moeten ze anderzijds juist niet groter. Per saldo lijkt het huidige control formaat prima, voorlopig mooi zo laten. Complimenten. Alleen euh.. het vergrootglas en het kruis _zitten_ nu toch al links?

**Comment by BaDu-HSN** [comment]
Ik doelde op de iconen in de zoek balk:
![image](https://cloud.githubusercontent.com/assets/21307438/20464319/c88a9102-af45-11e6-9f9b-22b4c97015d3.png)
Die aan de rechterkant van het invoerregel

**Comment by BaDu-HSN** [comment]
FIXED
dmv @media query selectors voor 240 en 320px
