### ISSUE TITLE
Legenda figuur actualiseren

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#39]
Het legenda figuur uit de netkaart is hopeloos veroudert en moet worden geactualiseert.
![image](https://cloud.githubusercontent.com/assets/21307438/20495365/0e0d3cda-b021-11e6-9652-923010184d4f.png)

**Comment by BaDu-HSN** [comment]
Inmiddels een scriptmatige oplossing bedacht (gebaseerd op stijlen.xml)
![afbeelding](https://cloud.githubusercontent.com/assets/21307438/20517062/aee457c4-b099-11e6-9bda-d3a593c90e8d.png)
@HansNien is dit akkoord?

**Comment by HansNien** [comment]
Fijn, mooi stukje werk! :-)
Akkoord is het zeker, want een scriptmatige oplossing staat ook in de bijbel als belangrijk nastreefbaar ding vanwege het bezwaar met ruimtegebrek en het niet flexibele gedrag van statische PNG-afbeeldingen. Je ziet dat die PNG sinds versie 4.0 niet meer is veranderd en mij was dat een doorn in het oog. Een scriptmatige oplossing is elegant, beter te gebruiken en het past qua styling mooier bij het huidige uiterlijk.

Paar dingetjes die nog van belang kunnen zijn: de hoogte van de blokken in de legenda kan iets smaller, zodat we dan nog ruimte houden voor het tonen van een voorbeeld spanningspictogram, het symbool voor _Netsituatie_, eventueel een paar symbolen voor _Bedrijfsmiddelen_ (converters, trafo, communicatietoren, compensatiemiddelen) en wellicht de netopening.

**Comment by BaDu-HSN** [comment]
Zo dan:
![afbeelding](https://cloud.githubusercontent.com/assets/21307438/20521490/c4222456-b0ab-11e6-8922-28e17ccaad70.png)

**Comment by HansNien** [comment]
Hmm, ik bedoelde eerder dat de gekleurde blokken zelf ietsje platter zouden worden. De tussenafstand tussen de teksten rechts is trouwens precies goed zo.

**Comment by BaDu-HSN** [comment]
Derde poging :)
![afbeelding](https://cloud.githubusercontent.com/assets/21307438/20522164/1a183b22-b0af-11e6-9b68-a62e961517d5.png)

**Comment by BaDu-HSN** [comment]
FIXED => closed

(evt toevoegingen van iconen via een nieuw issue)
