### ISSUE TITLE
Site aanpassen rondom live gaan Versie 6

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#41]
Pas tegen de tijd dat het zover is.
Tevens niet echt scripting, maar wel betrekking hebbend op vooral de webversie vanwege de disclaimer (essentieel).
Aanpassen documentatie, disclaimers, belangrijke links en andere relevante dingen op de site. De nieuwe situatie betreft zoals het nu lijkt een systeem met een webkaart en een versie die in GE kan worden gebruikt, goeddeels conform de huidige situatie. Vanaf versie 6 live veranderen versies uit de 4-serie in _abandonware_.

**Comment by BaDu-HSN** [comment]
Betreft minimaal de volgende URL's:
- [ ] http://www.hoogspanningsnet.com/google-earth/standaardnetkaart/
 Wellicht deze helemaal herschrijven of een nieuwe pagina voor de webkaart maken (GE blijft in de lucht)

- [ ] http://www.hoogspanningsnet.com/google-earth/standaardnetkaart/gebruiksaanwijzing/
Wellicht ook nieuwe pagina maken tbv de webkaart

- [ ] http://www.hoogspanningsnet.com/netkaart/disclaimer/
Wellicht kan deze blijven as-is

- [ ] http://www.hoogspanningsnet.com/netkaart/faq/
Toeven vragen mbt webkaart en checken bestaande teksten

- [ ] http://www.hoogspanningsnet.com/google-earth/screenshots/
Nieuwe pagina maken voor webkaart screenshots?
Aanpassen screenshots voor de balloons

- [ ] http://www.hoogspanningsnet.com/
Aanpassen netkaart links op de frontpage (implementeren webkaart)

- [ ] http://www.hoogspanningsnet.com/google-earth/standaardnetkaart/release-shortlist/
Toevoegen release V6.0

- [ ] http://www.hoogspanningsnet.com/google-earth/standaardnetkaart/release-notes/
Toevoegen release V6.0

**Comment by HansNien** [comment]
03dec16 - Disclaimer en FAQ reeds aangepast. FAQ is nu iets voor de muziek uit.

**Comment by HansNien** [comment]
10maa17 - nieuwe gebruiksaanwijzing voor de webkaart opgeleverd. (Bestaande exemplaar voor GE krijgt eerst nog opwaardering voordat dit punt afgevinkt wordt.)

**Comment by HansNien** [comment]
19apr17 - Bannertje vanaf de voorpagina is aangepast (styling in lijn gebracht met de huisstijl die deze winter een kleine wijziging onderging) en op de achtergrond reeds in gereedheid gebracht. Met één klik onder spanning te brengen op T=0. Wijziging URL is nodig vanwege de link welke webkaart.hoogspanningsnet.com wordt.

**Comment by HansNien** [comment]
25apr17 - Longlist en Shortlist aangepast.

**Comment by HansNien** [comment]
25apr17 - Pagina met screenshots van de netkaart toegepast in GE aangepast. Gevalletje goed genoeg is goed genoeg.

**Comment by HansNien** [comment]
25apr17 - In principe zijn alle pagina's nu gewijzigd. Op de dag van de release (29 april, meen ik) volgt er een half uurtje omkatten en omwisselen. Daarna kan dit punt worden afgestreept.

**Comment by BaDu-HSN** [comment]
Hulde!

**Comment by HansNien** [comment]
Op wat marginaal gepruttel na (er zwerft vast nog wel ergens een gebroken link rond en de menuposities vereisen nog wat schuifwerk) kan deze dicht.
