### ISSUE TITLE
Schrijven handleidingen bij webkaart (V6.0)

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#42]
- [x] Er moet een handleiding komen voor de normale gebruikers
- [x] Er moet een handleiding komen voor de editors

**Comment by HansNien** [comment]
Even afhankelijk van wat het handigst is. Ik denk dat Bas de handleiding voor de editors het beste schrijven kan, omdat de tool ook door jou gebouwd is. Wat betreft de handleiding voor normale gebruikers: die kan mooi de rol van de brakke gebruiksaanwijzing overnemen die nu op de site stof vangt. Ik wil die wel oppakken, dat voorkomt dubbel werk omdat de twee documenten (bestaande brakke gebruiksaanwijzing en nieuw te schrijven handleiding) dan één kunnen worden.

**Comment by BaDu-HSN** [comment]
OK, maar de handleiding voor Editors is eigenlijk heel simpel:
Klik op een item op de kaart en in de balloon klik op de ID
Vervolgens scroll je naar onderen en klik je op login to edit
En kan je de gegevens wijzigen.
Verder nog wat hints mbt de in te vullen gegevens (die ook in het editscherm al kunnen worden weergegeven).

Voor de Beheerders krijg je er evt nog een knop bij voor het wissen van het item.

**Comment by HansNien** [comment]
Handleiding voor normale gebruikers voor de webkaart is inmiddels klaar, zie [](http://www.hoogspanningsnet.com/netkaart/handleiding/). (Voor de GE- en GISgebruikers moet ik nog wat schrijven.)

**Comment by BaDu-HSN** [comment]
Een link naar de handleiding en de webkaart toegevoegd aan de settings-sidebar.

**Comment by HansNien** [comment]
Handleiding voor editors is inmiddels ook klaar. Zie http://www.hoogspanningsnet.com/netkaart/handleiding-editors/. Is het nog nodig om iets voor de beheerders te schrijven waarin bijvoorbeeld het youtroepfilmpje dat Bas gemaakt heeft kan worden ingebed ofzo, of veronderstellen we de handelingswijze voor beheerders voldoende bekend?

**Comment by BaDu-HSN** [comment]
Voor de editors handleiding:
De plaatjes mbt het inloggen zijn licht veroudert, deze ondersteunen inmiddels de taalinstelling van de gebruiker en worden niet meer alleen in het Engels weergegeven.

Misschien de plaatjes nog even aanpassen?

**Comment by BaDu-HSN** [comment]
tav de beheerders handleiding geldt dat deze geen extra functionaliteit hebben in de webkaart dan de editors, de handleiding voor beheerders in GE is nog steeds van kracht.

**Comment by BaDu-HSN** [comment]
De handleiding voor gebruikers is nog niet OK op het punt van de instelling view opslaan:
![afbeelding](https://cloud.githubusercontent.com/assets/21307438/24542503/2d21d590-15fc-11e7-929e-85fcb3946a11.png)
Deze instelling zzorgt ervoor dat de laatste view en zoom worden opgeslagen zodat de kaart de volgende keer op dezelfde positie en view wordt geopend. Samen met de instellingen layers opslaan kan je je kaart exact weer zo weergeven als toen je de browser af sloot.

**Comment by HansNien** [comment]
Beide bijgewerkt.
