### ISSUE TITLE
Volgorde iconen is verkeerd

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#43]
Iconen moeten worden weergegeven in de volgende volgorde (van onder naar boven):
- Masten
- Knoopunten
- Stationsiconen

**Comment by BaDu-HSN** [comment]
Gekeken naar toepassen van pane in de layer definitie, dit lijkt niet ok te werken.

**Comment by HansNien** [comment]
Daarop inhakend, misschien moet er voor alle soorten entiteiten met labels überhaupt wel een hiërarchie op spanning worden ingesteld. Denkend aan dit probleem kan het wellicht beter zijn om 380 kV _altijd_ boven 150 kV weer te geven, enzovoort.

![oersoep](https://cloud.githubusercontent.com/assets/23345566/20884797/afa1b00e-baed-11e6-9185-80326ad165f0.png)

**Comment by BaDu-HSN** [comment]
Dat is een van de problemen die het gevolg zijn van deze bug.
Het is erg lastig om in leaflet de z-index te sturen.

**Comment by HansNien** [comment]
Dat is eigenlijk wel apart. Je zou denken dat bijna iedereen die kaarten maakt (van wat dan ook) al heel snel een custom Z-index nodig heeft. Als Leaflet daar moeite mee heeft is het net als het bouwen van een luxewagen zonder ruitenwissers: onlogisch dat het er niet is.

**Comment by BaDu-HSN** [comment]
Aanleiding om toch nog eens te kijken of OpenLayers 3 misschien niet toch een betere keuze is.

**Comment by BaDu-HSN** [comment]
Kan niet worden gefixed
