### ISSUE TITLE
Cirkeltje zoekfunctie verdwijnt niet

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#47]
Een echte hinderlijke bug is het niet, maar als je de zoekfunctie gebruikt, gevonden hebt wat je zoekt en daarna het kruisje (cancel) indrukt, dan verdwijnt het zoekvenster netjes maar blijft het cirkeltje staan. Er lijkt geen enkele manier te zijn om het cirkeltje te doen verdwijnen behalve de hele netkaart F5'en.
Nu zijn er ergere dingen, maar het is eleganter als bij 'cancel' de hele zoekopdracht voltooid is en het cirkeltje dan mee verdwijnt.

**Comment by BaDu-HSN** [comment]
FIXED

Correct, Dit is echter de zoekfunctie zoals opgenomen on v01 van de webkaart.
De zoekfunctie in de nieuwe versie (v02) gebruikt een marker, welke na het wissen van de zoekterm (via het kruisje) weer verdwijnt.
