### ISSUE TITLE
Resolutie getallen op de legenda heeft grensproblemen

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#48]
De getallen zoals ingeklopt in de legenda hebben een probleem met afrondingen boven 10 kV. De groep 145-170 kV en 170-245 kV hebben bijvoorbeeld de waarde 170 kV gemeenschappelijk. Hier is dat niet zo'n punt omdat die waarde niet gebruikt wordt, maar er is er ook zo eentje bij 66 kV. De huidige notatie is wenselijk om te voorkomen dat de getallen te lang worden, maar het geeft toch wat verwarring. (Ik heb geen goed idee over hoe dit het hoofd kan worden geboden.)

**Comment by BaDu-HSN** [comment]
Ha idd, ik heb uit de stijlen.xml de naam van het betreffende netvlak genomen (zonder de tekst "Netvlak ").
Wellicjt maken we deze naam op kritische punten wat anders?

**Comment by BaDu-HSN** [comment]
Ik heb de netvlak namen in de stijlen.xml aangepast zodat grensproblemen niet meer optreden.

FIXED en CLOSE
