### ISSUE TITLE
Categorie Spanningsloos op de legenda mag wel een randje

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#49]
Inherent aan wit of halftranspa wit op een witte achtergrond is dat je 'm niet ziet, waardoor mensen kunnen denken dat er iets is weggevallen. Een 1px border #cccccc om de witte strook bij Spanningsloos bovengronds en #dddddd om de grondkabelversie kan laten zien dat er toch twee dingen staan.

**Comment by BaDu-HSN** [comment]
Ik zal kijke of ik de CSS zover kan krijgen 👍

**Comment by BaDu-HSN** [comment]
Zoiets: 
![afbeelding](https://cloud.githubusercontent.com/assets/21307438/20886066/79da551e-baf4-11e6-82fc-57cbed7ff933.png)
Het is wat lastig om dit echt als zon streepje te krijgen

**Comment by HansNien** [comment]
Dit is CSS-gegenereerd? Kunnen we dan niet kiezen voor een omweggetje door er een afbeelding van te maken en die op de bewuste plek inline te tonen?

**Comment by BaDu-HSN** [comment]
Dat kan natuurlijk altijd, maar is niet zo netjes :)

**Comment by coreice** [comment]
Afbeeldingen hebben niet echt de voorkeur bij mij omdat dit op sommige schermen (met hoge DPI zoals smartphones of sommige laptops) nogal lelijk weergegeven wordt, nogal pixelig. 

Het stukje 'Spanningsloos' valt nu trouwens wel weg.

<img width="232" alt="schermafbeelding 2016-12-22 om 13 37 47" src="https://cloud.githubusercontent.com/assets/10442497/21425877/eae4de00-c84b-11e6-8f66-8f645aa315e5.png">

En verder, is het wellicht een idee spanningsniveau's die nu niet gebruikt worden, ook niet weer te geven?

**Comment by HansNien** [comment]
Dan noemen we Spanningsloos toch gewoon nul (of als getal 0)? 
Geef het lijntje in elk geval niet teveel prioriteit.

**Comment by BaDu-HSN** [comment]
@coreice : Op welke OS/Browser wordt die spanningsloos zo weergegeven? (te lange tekst)
Op mijn systemen Win10/Ubuntu met FF, Chrome en IE11 en MS-Edge gaat het allemaal prima.

Verder : bedoel je met ongebruikte spanningen niet weergeven, de spanningsen die op dat moment worden weergegeven op de netkaart? (alleen met moeite te proggen) of de spanningen die op dit moment in de netkaart database zitten? (eenvoudig te maken).

**Comment by coreice** [comment]
@BaDu-HSN Apart, op FF/Safari/Chrome op de Mac gaat het mis. 

Ik bedoel de makkelijke methode, spanningen weglaten die op dit moment niet in de database zitten. Dan hoeft de gebruiker überhaupt niet met die informatie opgescheept te worden :-).

**Comment by BaDu-HSN** [comment]
@coreice : Kan je kijken of het nu beter gaat met de overloop van de legenda?
Ik ben van het gebruik van Roboto in de legenda sidebar af gestapt

**Comment by BaDu-HSN** [comment]
![afbeelding](https://cloud.githubusercontent.com/assets/21307438/22930942/ebf384c6-f2c2-11e6-8987-cf7b90a3a63e.png)
Dit is het geworden
CLOSE
