### ISSUE TITLE
lay-out edit scherm van entiteit-eigenschappen-ballon.

### ISSUE THREAD

**Issue by Knarvel** [Hoogspanningsnet/Webkaart-scripts#5]

**Comment by Knarvel** [comment]
-maak dit scherm zo groot mogelijk, de kaart doet er immers nu even niet toe. probeer een scrollbar te vermijden.
- zet de knoppen zo dat deze altijd in beeld blijven
- zet een entiteit-delete knop in de edit-box.
- zet een geo-coordinaten display in de edit box met een knop deze te kopieren, danwel naar een geohack pagina te springen.
- zet een entiteit-export knop in de edit box die alle entiteit gegevens in een textbestandje schrijft.
- zet de inlog-status op een bepaald apparaat in een coockie of ergens anders voor GE

**Comment by Knarvel** [comment]
Nu dat ik ook met de "Bahnstrom"begonnen ben, erover nadenkende, zou het handig zijn de AC/DC parameter met een extra keuze uit te breiden. Nu is het AC oof DC, beter zou het DC, AC 50 Hz, AC 16,7 Hz en evtl AC 60 Hz als inhoud toe te staan. Het liefst met een dropdown keuzelijst.
Had ik hier al om dd-keuzelijsten voor de mast- en stationstypen en ondersoorten parameters gevraagd?

**Comment by BaDu-HSN** [comment]
Moet ook in een css verwerkt gaan worden (coreice ook assigned)

**Comment by BaDu-HSN** [comment]
Ook verwerken in de GE-scripts (zie issue https://github.com/Hoogspanningsnet/GE-scripts/issues/12)

**Comment by BaDu-HSN** [comment]
Ik zit hier even in detail naar te kijken maar er zijn in het voorstel van knarvel enkele punten die me niet handig lijken om te maken:

_-maak dit scherm zo groot mogelijk, de kaart doet er immers nu even niet toe. probeer een scrollbar te vermijden._
BaDu: het kan helaas in GE niet groter dan de afmetingen van de balloon, bij deze afmetingen is niet mogelijk een scrollbar te vermijden
    _zet de knoppen zo dat deze altijd in beeld blijven_
BaDu: dat moet kunnen
    _zet een entiteit-delete knop in de edit-box._
BaDu: Dit kan alleen indien diegene voldoende rechten heeft (beheerder en geen editor)
    _zet een geo-coordinaten display in de edit box met een knop deze te kopieren, danwel naar een geohack pagina te springen._
BaDu: Het is me niet duidelijk wat je hier precies mee wilt, naar welke geohack pagina moet je dan springen. De geocoordinaten voor verbindingen kunnen echt heel lang zijn, dus ik neem aan dat je dit alleen voor punt informatie wilt.
    _zet een entiteit-export knop in de edit box die alle entiteit gegevens in een textbestandje schrijft._
BaDu: Opzich wel mogelijk, maar wat wil je hiermee bereiken? Waarom is dit handig? Welk formaat moet de informatie in het tekst bestand hebben? 
    _zet de inlog-status op een bepaald apparaat in een coockie of ergens anders voor GE_
In GE / webkaart wordt voor de inloggegevens van cookies gebruik gemaakt (nu al), maar de het cookie wordt na afsluiten van GE of webbrowser weggegooid. Eigenlijk wil ik deze strategie van uitloggen bij afsluiten van een sessie (zo heet het officieel) wel vasthouden, het levert nl wat veiligheids problemen op wanneer je de cookies bijv x-dagen bewaart.

**Comment by Knarvel** [comment]
zet een entiteit-delete knop in de edit-box.
BaDu: Dit kan alleen indien diegene voldoende rechten heeft (beheerder en geen editor)
Dat is ook goed zo, maar deze knop kan dan toch bij een lagere bevoegdheid gedeaktiveert of onderdrukt worden

zet een geo-coordinaten display in de edit box met een knop deze te kopieren, danwel naar een geohack pagina te springen.
BaDu: Het is me niet duidelijk wat je hier precies mee wilt, naar welke geohack pagina moet je dan springen. De geocoordinaten voor verbindingen kunnen echt heel lang zijn, dus ik neem aan dat je dit alleen voor punt informatie wilt.
Als het een puntvormig objekt is, dan ja, Bij lijnen en vlakken zou je het midden van het huidige beeld kunnen aannemen.  Oproep met https://tools.wmflabs.org/geohack/geohack.php?language=en&params=48.585556_N_12.220556_E_ (met de juiste waarden vervangen)

zet een entiteit-export knop in de edit box die alle entiteit gegevens in een textbestandje schrijft.
BaDu: Opzich wel mogelijk, maar wat wil je hiermee bereiken? Waarom is dit handig? Welk formaat moet de informatie in het tekst bestand hebben?  Eigenlijk alleen voor lijnen handig, als je als ik aan lijnen en hun punten wilt knoeien is dit makkelijk geen speciaal formaat, platte texr in een .txt file. Filenaam = objektnaam.txt
