### ISSUE TITLE
Kleur luchtlijnen netvlak 30-40,4 kV iets schuiven

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#50]
Klein dingetje, op suggestie van Bavo. Of de luchtlijnen van 30- en 36 kV een stukje kunnen opschuiven qua kleur om zo het onderscheid beter zichtbaar te maken. Huidig is #C479C4, verzoek is of dat het voor de luchtlijnen naar #9E469E kan.

**Comment by BaDu-HSN** [comment]
FIXED
Webkaart (testserver)
GE netkaart
