### ISSUE TITLE
Verplaatsen enkele pagina's (URL's) en aanpassen menunamen

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#51]
De huidige pagina's met release notes (longlist en shortlist), de toekomstige online gebruiksaanwijzing, de namen van de koppen in de menu's ("Google Earth netkaart") en de screenshotpagina moeten van URL worden veranderd, weg van (...)google-earth(...) en naar (...)net.com/netkaart/whatever. 
Bestaande links moeten in eerste instantie een redirect worden om ongemakken quick and dirty te voorkomen.

**Comment by HansNien** [comment]
Shortlist en Longlist inmiddels verplaatst, nu bereikbaar onder /netkaart/releasenotes-shortlist en onder /netkaart/releasenotes-longlist.

**Comment by BaDu-HSN** [comment]
Wanneer de URL's allemaal bekend zijn, plaats ze dan even hier, dan zorg ik dat de boel wordt aangepast.

**Comment by HansNien** [comment]
Roger that.

**Comment by BaDu-HSN** [comment]
Ook verwerken GE-scripts: (issue https://github.com/Hoogspanningsnet/GE-scripts/issues/10)

**Comment by HansNien** [comment]
Gebruikershandleiding voor de webkaart pak ik op. Deze wordt momenteel herschreven en krijgt de vorm van een webpagina op de mainsite. (Geen gezeur met PDF-documenten.)

**Comment by HansNien** [comment]
Zie item #42. Handleiding is klaar, er kan naartoe worden gelinkt.

**Comment by BaDu-HSN** [comment]
Verwerkt en dus CLOSED
