### ISSUE TITLE
Bugje met de letter G

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#52]
Mierenn(____)n naar een hoger niveau getild. Piepklein bugje deze keer. De letter g in de huidige labels komt soms niet goed door, zodat er soms 'Weabera' of 'Tihanae' lijkt te staan. Met name in het fontformaat dat voor 100+ kV wordt gebruikt valt het onderste stuk van de g er soms af, maar dit lijkt niet consequent omdat hij er soms alsnog wel staat (zie screenshot). Ik heb geen idee hoe of wat dit veroorzaakt, maar FF en Chrome doen dit alle twee. 

![probleem met de g](https://cloud.githubusercontent.com/assets/23345566/20887716/203d0aee-bafc-11e6-9b6d-b0456c0061c2.JPG)

**Comment by BaDu-HSN** [comment]
Ah idd een klein probleempje in de icoongenerator.
De laag hangende letters verliezen hun zaakje.
Ik zal het aanpassen

**Comment by BaDu-HSN** [comment]
FIXED
	if ($naam <> '' and $nrsp == 1) {
		$height = 24;
	} else {
