### ISSUE TITLE
Aanbouwen van een 'wis-log'

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#54]
Naar aanleiding van een discussie op het forum over gewiste objecten. Alle wijzigingen aan objecten worden gelogd, maar bij wissen wordt ook deze log verwijderd. Dat is geen probleem, maar het is daardoor niet meer te achterhalen wie of waarom een entiteit gewist werd. Idee is nu om bij wissen een optioneel veld 'reden' door te voeren, waarbij na wissen van het object het ID-nummer, de roepnaam en de ingegeven reden voor wissen gelogd blijven, liefst inzichtelijk via de backend en voor iedereen met beheerdersrechten. Zo kan men van elkaar zien waarom een bepaald object gewist werd en worden discussies of vragen voorkomen.

**Comment by BaDu-HSN** [comment]
Verplaatst naar Beheer-scripts https://github.com/Hoogspanningsnet/Beheer/issues/4
