### ISSUE TITLE
Veranderen symbool in de knop bij menu inklappen

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#56]
Zoals besproken op de vergadering. Momenteel staat daar een symbool dat sterk lijkt op een knop Vernieuwen zoals browsers die gebruiken. Die is enigszins misleidend. Er werd gekozen voor een pijltje dat naar links wijst. Een korte blik in het font (awesome) leert dat het symbool voor _chevron left_ of nog beter _angle double left_ hier van nut kan zijn. Het betreft &#Xf103;

**Comment by HansNien** [comment]
Okee, daar maakt ie iets heel lelijks van. Zonder de spaties bedoelde ik symbool  & # x f 1 0 3 ;

**Comment by coreice** [comment]
Bij nader inzien denk ik dat de icoontjes gewoon hetzelfde kunnen blijven. Het principe dat je er weer op kunt klikken om te sluiten, is volgens mij duidelijk genoeg. Anders zou ik inderdaad voor een chevron achtige pijl '<' kiezen.

**Comment by HansNien** [comment]
Het idee/voorstel van Mark is op zich ook niet verkeerd. Niet aan gedacht eigenlijk. Het ziet er net iets verzorgder uit als er een ander icoontje staat, maar verder is er eigenlijk geen reden.

**Comment by BaDu-HSN** [comment]
Ik zit zelf te denken aan het icoon blauw te kleuren wanneer de sidebar open is en normaal wanneer deze onzichtbaar is.
