### ISSUE TITLE
Projectiehiërarchie namen en iconen stations op de webkaart

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#57]
Conform de vergadering. In de interface van GE worden de namen van stations zo mogelijk niet boven elkaar weergegeven tenzij het niet anders kan. De webkaart heeft zo'n functie niet. Dat is op zich nog tot daar aan toe, maar er is ook geen functionaliteit die bepaalt dat de namen en pictogrammen van entiteiten op hoger gelegen netvlakken boven die van lagere netvlakken worden weergegeven. Dit levert oersoep op bij plekken waar het hoogspanningstechnisch te doen is. Voorstel is om projectiehiërarchie in te voeren voor de verschillende netvlakken, waarbij namen en pictogrammen van de netvlakken als het ware gestapeld worden en het hoogste (dominante) netvlak telkens bovenop ligt wanneer er overlap verschijnt.

**Comment by BaDu-HSN** [comment]
Duplicate from https://github.com/Hoogspanningsnet/Webkaart-scripts/issues/43
