### ISSUE TITLE
Mogelijkheid tot het soms tonen van een melding / splash screen

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#58]
Alleen van belang voor de webkaart. De mogelijkheid tot het soms kunnen weergeven van een klein venster vóór de kaart, waarin een korte tijdelijke mededeling kan staan. 

Bij langdurige problemen of statusmeldingen die werkelijk van belang zijn voor de eindgebruiker kan het een toevoeging zijn om bijvoorbeeld klein bovenin een venster of zinnetje tekst te kunnen weergeven die in beeld blijft en dingen kan zeggen zoals "Stationspictogrammen tijdelijk niet beschikbaar vanwege storing. Er wordt aan gewerkt, pardon voor het ongemak".

**Comment by BaDu-HSN** [comment]
Goed plan, zoiets?
https://camo.githubusercontent.com/51dc186beb2648baf94437986287461e85e8279a/687474703a2f2f6d61707368616b6572732e6769746875622e696f2f70726f6a656374732f6c6561666c65742d636f6e74726f6c2d77696e646f772f6c6561666c65742d636f6e74726f6c2d77696e646f772e6a7067

**Comment by HansNien** [comment]
Ja, precies dat! Mooi dat dit lijkt te kunnen. Nu maar hopen dat we 'm zelden nodig hebben.

**Comment by BaDu-HSN** [comment]
Om een alert weer te geven ingeval van een storing oid, zet string Alertmessage met de mededeling.
Deze string staat in NetkaartSettings.js

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/22466737/f540ae02-e7c1-11e6-907d-f8a1887b2958.png)

Het welkomscherm wordt weergegeven wanneer een gebruiker nieuw is of minimaal 30 dagen de kaart niet heeft bekeken. De weergegeven tekst kan worden bepaald in NetkaartSettings.js met de string WelcomeMessage

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/22466764/07f7f8f2-e7c2-11e6-9cb8-eda8ffbbeed3.png)
