### ISSUE TITLE
Attribution icon transparant, is dat mogelijk

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Webkaart-scripts#64]
Onderzoeken of de attribution circle transparant gemaakt kan worden.

**Comment by HansNien** [comment]
Wat is hiervoor de meest wenselijke weg? Via het script de hele afbeelding gedeeltelijk transpa maken, of een PNG-versie aanleveren die alleen het witte rondje gedeeltelijk transpa heeft? Ik vermoed het laatste vanwege de duidelijkheid van e.e.a.

**Comment by BaDu-HSN** [comment]
Ik denk dat de ring in css transparant te maken is. Het logo zullen we wellicht met een transparantie moeten gaan voorzien

**Comment by BaDu-HSN** [comment]
Ik twijfel hier, de mogelijkheid is er (in CSS vrij eenvoudig).
Maar het is icoon is al heel bescheiden en ik zou het niet nog bescheidener willen maken.
@HansNien @coreice wat is jullie mening?

**Comment by HansNien** [comment]
Net eens gekeken, misschien is de huidige weergave ook wel goed zo. Logo is nu tegen elke achtergrond zichtbaar, lufo, mapbox of OSM maakt niet uit. De ring lijkt nu reeds 20% transpa o.i.d. te zijn. M.i. voorlopig niets meer aan doen eigenlijk.

**Comment by BaDu-HSN** [comment]
Wont FIX
