### ISSUE TITLE
Zoomlevel tonen verbindingen <30 kV een stap dieper zetten

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#67]
Enigszins verwant aan issue #55 maar niet helemaal gelijk. Voortkomend uit een opmerking dat het wel erg vol kan lopen met labels en verbindingen op MS-niveau in sommige regio's. Ook besproken tijdens de vergadering.
Bij zoomlevel 10 worden nu alle verbindingen getoond. Vanaf zoomlevel 11 worden ook de stationslabels met pictogrammen getoond. Zoomlevel 11 groeit daardoor wel erg dicht met 20-25 kV in bijvoorbeeld de regio Rotteram. Voorstel is om het tonen van verbindingen <30 kV nog een zoomlevel dieper te zetten, vanaf zoomlevel 12 en dieper. Ook de pictogrammen van stations met een hoogste spanning <30 kV zou eventueel verschillend kunnen worden gemaakt van alles erboven, zoals vanaf zoomlevel 12, zodat het dichtgroeien enigszins getemd wordt.
![zoomlevel 11 en 12](https://cloud.githubusercontent.com/assets/23345566/21525455/aaf24130-cd1d-11e6-829c-036e20ca802e.PNG)

**Comment by BaDu-HSN** [comment]
Ok im in

**Comment by BaDu-HSN** [comment]
Het lijkt me het handigst voor de iconen twee zoom niveaus te identificeren:
$HVIconZoomLevel : Bij dit niveau komen de iconen groter dan HV in beeld (>=110kV)
$MVIconZoomLevel: bij dit niveau komen de MV iconen in beeld (<110kV).
De waarden van het zoom;level moeten we nog even over nadenken (12 lijkt voor MV wel OK)
Dit alles geeft een wat mooiere overgang.

**Comment by HansNien** [comment]
Mee eens. Het tonen van de labels vanaf verschillende zoomlevels was nog niet eens in me opgekomen als aparte actie van het tonen van de verbindingen onderling. Ik heb net eens even die zoomlevels geprobeerd die je noemt en dan ontrolt zich het volgende inzicht voor het tonen van dingen. 

- Level 1-7: koppelnet 245 kV en hoger, geen pictogrammen en labels
- Level 8: netten netvlak 72,5 kV en hoger, geen pictogrammen en labels
- Level 9: netten netvlak 72,5 kV en hoger, labels en pictogrammen koppelnetstations >170 kV
- Level 10: netten netvlak 30 kV en hoger, labels en pictogrammen stations >72,5 kV
- Level 11: alle netten, labels en pictogrammen > 30 kV en hoger
- Level 12-18: alle netten, alle pictogrammen 

We hebben dan een soort constructie waarbij de labels één niveau na-ijlen op de weergave van de verbindingen. Er is dan altijd een stap aanwezig waarin de samenhang met het onderliggende net dan blijkt uit de stations uit een hoger netvlak die voor het nieuw verschenen net een soort koppelfunctie vervullen. 

(Het is maar een idee, graag erop schieten. :-) )

**Comment by BaDu-HSN** [comment]
De voorgestelde waarden geven wat serverproblemen bij sommige zooms, metname op grote schermen neemt het aaantal verbindingen en iconen wat van de server moet komen bestwel grote vormen aan (>600 iconen). 
Na een beetje experimenteren ben ik op de volgende tabel gekomen:
![afbeelding](https://cloud.githubusercontent.com/assets/21307438/22252331/1a00d4f2-e24e-11e6-8e18-b878b4ecd028.png)
Deze geeft mi een goede balans tussen serverbelasting en kaartdetaillering

**Comment by BaDu-HSN** [comment]
FIXED with commit  	81a409a
