### ISSUE TITLE
Spinner (laden) blijft soms erg lang staan

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#73]
Op het ene moment werkt de webkaart heel vlot en is de content en de achtergrond binnen enkele seconden helemaal geladen. De spinner verdwijnt dan vlot. Op andere momenten is de kaart wat trager. Soms duurt het dan tien seconden of langer om de content te laden. Opmerkelijk is echter dat de spinner soms helemaal niet meer verdwijnt, ook al ziet de content er wel volledig geladen uit. 
Hoe of waarom dat kan weet ik niet, maar het wekt de indruk dat er nog steeds meer in aantocht is zodat de gebruikers die de netkaart nog niet kunnen dromen nu juist alsnog de indruk krijgen dat ie is vastgelopen. 

Kunnen we misschien een functie op de spinner zetten dat die (hoe dan ook) na een halve minuut niet meer wordt getoond, ongeacht of de content volledig is geladen of nog niet? Of is dit een vreemde gedachte?

**Comment by BaDu-HSN** [comment]
Timeout is wel mogelijk

**Comment by HansNien** [comment]
Maar dan valt de hele kaart toch uit? Of houdt hij dan gewoon op met laden?

**Comment by BaDu-HSN** [comment]
De spinner wordt na 15 seconden gestopt, de rest gaat wel gewoon door.

**Comment by BaDu-HSN** [comment]
REOPENED: Spinner lijkt niet meer uit te schakelen, alleen na timeout (15 sec)

**Comment by HansNien** [comment]
Lijkt zich opnieuw voor te doen of niet volledig opgelost te zijn. In zowel Chrome als FF blijft ie tot in lengte van dagen rondjes draaien. F5 helpt éénmalig, maar na een keer zoom/pan of schuiven blijft hij alweer hangen. 
Aan oplossen gerelateerd: kan het ding ook naar de linker onderhoek van het scherm? Er is dan nog wel te zien dat er al dan niet terecht iets aan het laden is, maar hij staat niet meer in de primaire beeldfocus. Het beste van twee werelden.

**Comment by BaDu-HSN** [comment]
Hij zou onder de zoom knoppen kunnen komen:
https://github.com/ebrelsford/Leaflet.loading
Nog wel even kijken of deze lief speelt met de geoJSON layers
