### ISSUE TITLE
Tekstballonnen willen niet laden in de webkaart

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#81]
Server error 500 bij het weergeven van de tekstballonnen in de webkaart, althans op de computer die ik hier gebruik (Win 7, Chrome en FF). Op de telefoon doet alles het normaal en ook in de GE-interface geen problemen. Een en ander ontstond ergens rond 1700 uur vandaag. F5 helpt niet. Rest van de content (grafisch) en alle menu-opties werken normaal. Ik weet niet of anderen dit ook hebben en ben momenteel niet in de positie een andere computer te proberen.

![storing ballonnen webkaart](https://cloud.githubusercontent.com/assets/23345566/22799674/fcf86ae4-ef06-11e6-81e0-29479f0137c6.JPG)

**Comment by BaDu-HSN** [comment]
Ik kan deze niet reproduceren, alles lijkt hier goed te werken.
Graag meer info indien deze fout nogsteeds of opnieuw optreed.
Info benodigd: Tijdstip, Welke balloon (welke ID), OS, browser, eventuele stappen vooraf gaand aan de fout.

Voor nu sluit ik dit issue.
Mochten er toch nog problemen blijven bestaan kan dit issue weer geopend worden
