### ISSUE TITLE
Positie nieuwe spinner verplaatsen naar onder de onderste menuknop?

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#82]
Klein dingetje maar. De nieuwe spinner op de positie onder de zoomknoppen is een grote verbetering, maar er is een klein nieuw euveltje: hij drukt de knoppen voor locatiebepaling, menu en instellingen omlaag. Wanneer je daar een van wil aanklikken en de spinner verdwijnt precies op dat moment (waardoor de knoppen omhoog schuiven), dan klik je net de verkeerde aan. Bepaald geen big deal, maar het zou oplosbaar zijn door de nieuwe spinner niet pal onder de zoomknoppen maar helemaal onderaan onder de onderste knop weer te geven. Daar kan hij straffeloos verschijnen en verdwijnen zonder de knopposities te beïnvloeden.

**Comment by BaDu-HSN** [comment]
http://ebrelsford.github.io/Leaflet.loading/separate.html

**Comment by HansNien** [comment]
Precies wat ik bedoelde. Mooi dat zoiets al bestaat. Hiermee zou het probleem terstond verdwijnen. Wat mij betreft doen.
