### ISSUE TITLE
Bovenbalk qua styling gelijktrekken met mainsite

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#84]
Op de mainsite is de bestaande groene bovenbalk van in totaal 29 pixels (vraag me niet waarom Jacob daar ooit voor koos) is nu voorzien van een blauw onderrandje, naar voorbeeld van wat de webkaart een dag eerder al toonde. 
De kleur groen (#CCE54A) klopt al op beide balken, maar de kleur van het onderrandje op de mainsite heb ik overgenomen van de letters van het logo (#2D5A9F) en het onderrandje is ook iets hoger gemaakt, namelijk 3 pixels. Kan het blauwe onderrandje op de bovenbalk van de webkaart daarmee gelijkgetrokken worden? (De balkhoogte van het groen zelf is prima als die geen 26 pixels is, dat boeit niets. Het zoekicoontje staat er nu prachtig mooi in, daar vooral niet meer aan sleutelen :-) )

![bovenbalk screenshot](https://cloud.githubusercontent.com/assets/23345566/22920917/b1507e44-f297-11e6-9307-be73504672ce.png)

Of we de letters van de naam HoogspanningsNet Netkaart en het versienummer ook in #666666 willen hebben zodat die beter opvalt tegen de lichtgroene kleur weet ik niet goed. Misschien juist niet, zodat het niet teveel de aandacht trekt.

**Comment by BaDu-HSN** [comment]
Done, ik heb de letterkleur ook aangepast naar #666666, persoonlijk vindt ik deze net iets mooier en duidelijker.
