### ISSUE TITLE
Error in laden sommige foto's in de zijkolom

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#85]
Excuses als ik voor de muziek uitloop omdat de zijkolom natuurlijk _work in progress_ is.
Deze verschijnt op mastpositie 68 van Dodewaard-Veenendaal. Het lijkt erop dat het formaat van die foto niet automagisch aan te passen is of dat een foto verwijderd is waarvan de link nog wel bestaat. (Verder geen idee, maar als een link dood is moeten we misschen een _graceful fail_ zien te overwegen.)

![error in de zijkolom bij laden foto](https://cloud.githubusercontent.com/assets/23345566/22938343/d570bdfe-f2db-11e6-9797-9ce82ba03fec.JPG)

**Comment by BaDu-HSN** [comment]
hmm  eens even kijken

**Comment by BaDu-HSN** [comment]
Done
Er wordt nu eerst gechecked of FotoURL een bestaand bestand is en of het ook echt een image bevat.
Indien niet het geval wordt de standaard geen foto beschikbaar weergegeven.

**Comment by BaDu-HSN** [comment]
CLOSED
