### ISSUE TITLE
Informatie bij mastposities (verkeerde veld aan term geknoopt)

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#86]
Klein dingetje slechts. Bij de ballon/kolom voor mastposities is simpelweg een verkeerd veld of een verkeerde veldnaam aan een reeds bestaande lijst met records verbonden.

![mastpositiekolom met verkeerde doorverbinding](https://cloud.githubusercontent.com/assets/23345566/22967904/a3f8c608-f368-11e6-8702-75ed0186b563.jpg)

De term _Subtype_ verwijst nu naar het mastmodel, terwijl de term _Mastmodel_ leeg is. Die was bedoeld andersom te zijn (bij mastmodel kan dan tonmast, donaumast, hamerkop, etc. staan, terwijl bij subtype de open informatie kan worden gegeven waar de pylon geeks helemaal op losgaan, IJsselmij-hamerkop generatie I). 
Het weergeven van de naam _Tonmast_ (zoals in dit voorbeeld) op één positie hoger zou het hele probleem al oplossen.

**Comment by BaDu-HSN** [comment]
hmmm dit geeft een erg onlogische koppeling tussen balloon en database velden.
Jouw voorstel geeft dit:
- display Mastmodel in de balloon is gekoppeld aan veld SubType in de mastentabel
- display SubType in de balloon is gekoppeld aan veld MastModel in de mastentabel

Eigenlijk zijn de database velden dus onjuist ingevuld :)

**Comment by BaDu-HSN** [comment]
Opgelost door de veldnamen in de masten tabel om te wisselen.
Veld SubType heet nu MastModel
Veld MastModel heet nu SubType
