### ISSUE TITLE
Tekst en taal feedbackformulier

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#91]
Op dit moment staat er een tekst boven het feedbackformulier. 
_Dank dat u wilt helpen met het verbeteren van onze netkaart! Vul de velden hieronder in, mochten wij nog vragen hebben nemen we contact met u op._

Dat lijkt een aanzet om tot een definitieve tekst te komen. Bij dezen een voorstel in het Nederlands:
_Dank dat u wil helpen met het verbeteren van onze netkaart, Vul alstublieft het formulier in. Mochten wij naar aanleiding van uw bericht nog vragen hebben, dan nemen we contact met u op._

Boven de kolom zou het woord _Meldformulier_ in hetzelfde, iets grotere font als waarin we objectnamen schrijven ook wel op zijn plek zijn. Net als het logootje rechtsonder.

Er is ook een probleem: hoe gaan we om met feedback vanuit het buitenland? Willen we dat eigenlijk wel? En hoe gaan we om met het taalprobleem? Feedback in het Frans zie ik niet zitten. Discussie openen in Schakelveld 51 hierover?

**Comment by BaDu-HSN** [comment]
Vertalen is al standaard, NL, DE en straks UK en FR
Voor lastige franstalige feedback berichten kunnen we altijd gebruik maken van shrek of powerlion (of gewoon google translate gebruiken, dan kom je er wellicht ook wel.

De teksten pas ik aan

**Comment by BaDu-HSN** [comment]
CLOSED
