### ISSUE TITLE
Veld Masthoogte default verbergen bij 0 meter

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#92]
Het veld _masthoogte_ wordt nu standaard weergegeven. Dat hebben wel meer velden, maar bij masthoogte staat er reeds een vooringevulde waarde in van 0 meter. Dat is eigenlijk fout in plaats van gewoonweg onbekend. Voorstel is om dat veld default te verbergen indien leeggelaten (dus bij 0).

**Comment by BaDu-HSN** [comment]
CLOSED
