### ISSUE TITLE
Uitlijning symbolen in knoppen

### ISSUE THREAD

**Issue by coreice** [Hoogspanningsnet/Webkaart-scripts#93]
In sommige browser lijken de symbolen _in_ de knoppen links te verspringen. Ook de (X) is soms niet uitgelijnd. Zie de screenshots.

Getest op MacOS 10.12.3 met Safari 10.0.3, Chrome 56.0.2924.87 en Firefox 53.0a2. 
Evenals mobiel op iOS 10.2.1 met Safari 10.0 en Chrome 56.0.2924.79.

![img_6523](https://cloud.githubusercontent.com/assets/10442497/23015415/fff12da4-f432-11e6-9f2f-b611c2db1812.PNG)

**Uitlijning symbolen in linkerknoppen**
Het verspringen van de symbolen in de knoppen links gebeurd alleen op Safari en Chrome op de smartphone. In Chrome op de desktop valt wel op dat als je met de muis eroverheen beweegt dat tie dan ook wat verschuift. Het verspringen vind echter niet plaats (ook niet in Safari of Firefox).

In Firefox in mobiele weergave modus gaat het dan weer goed. Ook op de desktop geen problemen.

<img width="375" alt="schermafbeelding 2017-02-16 om 10 29 06" src="https://cloud.githubusercontent.com/assets/10442497/23015378/d61deb2a-f432-11e6-9706-4c0d479deeae.png">

**Verkeerde uitlijning van de (X) bij de ballonnen**
Dit speelt in alle browsers die ik heb op de desktop. Op mobiel lijkt het ook aanwezig maar minder (?).

**Comment by BaDu-HSN** [comment]
Oef , das lastig debuggen omdat ik niet beschik over een apple apparaat.
Mooi is anders, maar er loopt geen bloed uit

**Comment by BaDu-HSN** [comment]
OK, lijkt erop dat het verspringen onder Chrome nu verholpen is.
Het verkeerd uitlijnen krijg ik op dit moment niet opgelost.
