### ISSUE TITLE
Doorverwijzing essentiële links

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Webkaart-scripts#94]
Enkele van de essentiële links (Over de netkaart) verwijzen niet goed door. Dat ligt overigens aan mij, ik heb die pagina's verplaatst naar een kortere URL. De pagina waar ze nu heen verwijzen is in een redirect veranderd. De nieuwe situatie:

- Bug/Update?
De link met _Bug/Update_ zouden we kunnen veranderen in het woord Feedback, om daarna het feedbackformulier te laten openen maar dan zonder vooringevuld ID-nummer. 

- Copyrights
Kan naar https://creativecommons.org/licenses/by-nc-nd/4.0/ , de opvolger van 3.0. 

- Release Notes
Kan naar http://www.hoogspanningsnet.com/netkaart/releasenotes-longlist/ , op nieuwe URL waar de term Google Earth uit is verdwenen

- Disclaimer 
Is correct.

Eventueel zouden we later nog een paar links kunnen toevoegen. Bijvoorbeeld _over de netkaart_ (verwijzend naar een pagina op de mainsite met algemene informatie en een korte gebruiksaanwijzing), iets als _GIS-gebruiker?_ (verwijzend naar een pagina waarop de huidige voor GE geschikte KML-versie te downloaden valt, samen met wat informatie) of misschien ook naar de FAQ-pagina.

**Comment by BaDu-HSN** [comment]
CLOSED
