### ISSUE TITLE
Datumweergave in ballons

### ISSUE THREAD

**Issue by Knarvel** [Hoogspanningsnet/Webkaart-scripts#98]
In de ballons wordt de datum van in en/of buiten-gebruikstelling nu alleen met het jaar aangegeven.... Voor alle net-modificaties in het verdere verleden is dit prima. We spraken er al kort over in de laatste netkaart bijeenkomst, en besloten toen er later nog eens naar te kijken. 
Naar aanleiding van de ons toegespeelde gegevens over de voeding van het spoorlijntje naar HvH, (met de nieuwe dienstregeling van 1 april gaat het station en alle kabels plat), zien we weer een situatie waar dit datums-formaat tekortschiet, immers zet je dit op 2017 dan is ie nu al weg, zet ik het op 2018 (als nu gedaan) staat ie er 9 maanden te lang in. 
Ik pleit ervoor om in de database alle jaartallen in een echte datum om te zetten, dus bv 1980 wordt 1 jan 1980, en in de textballon volledige datuminput mogelijk te maken. Waar niets beters weten nemen we standaard 1 jan van het bekende jaar aan, komt er bij speurwerk een betere datum boven water, dan vullen we die in.
Van aktuele zaken weten we de data zeer nauwkeurig, en het is jammer deze gegevens door afronding te laten verwateren.
Een eventuele toekomstige historie-funktie zal hierdoor ook mooier werken, maar vooral bouwen we op deze manier ook een kroniek van het hs-net op.

**Comment by BaDu-HSN** [comment]
Ik voel hier wel wat voor.

Overigens verdwijnt een object met jaaraanduiding 2017 pas op 1-1-2018 van de kaart.

**Comment by Knarvel** [comment]
Experimenteel heb ik dat anders gezien, maar dat is niet het eigenlijke punt. Belangrijk is de juiste datum daar waar we die weten...

**Comment by BaDu-HSN** [comment]
"Experimenteel heb ik dat anders gezien"
Als ik hiermee experimenteer, zie ik dat gedrag niet, graag voorbeelden.

**Comment by Knarvel** [comment]
aangaande mijn opm. van 24-2: dat had ik mis, het werkt zoals jij het schilderde.

**Comment by BaDu-HSN** [comment]
Inmiddels heb ik op mijn testserver de maand en dag velden toegevoegd aan de diverse tabellen.
Voor de webkaart en netkaart moeten de balloon definities nog aangepast worden, net als de definities van de edit schermen.

**Comment by Knarvel** [comment]
Is dat wel slim om 3 integers op te slaan ipv een echte datum? Op die manier kan je niet bestaande data ingeven. Als je de datums-validatie uit de weg wilt gaan, gebruik dan een calender control element.
Ik denk dat je met een echte datum altijd beter af bent.

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#42
